### ISSUE TITLE
Create project not working: "name" not given returned

### ISSUE THREAD

**Issue by pitchandtone** [m4tthumphrey/php-gitlab-api#103]
```
PHP Fatal error:  Uncaught exception 'Gitlab\Exception\ErrorException' with message '400 (Bad request) "name" not given' in /Users/john.milmine/Sites/gitlab_migration/vendor/m4tthumphrey/php-gitlab-api/lib/Gitlab/HttpClient/Listener/ErrorListener.php:47
Stack trace:
#0 /Users/john.milmine/Sites/gitlab_migration/vendor/m4tthumphrey/php-gitlab-api/lib/Gitlab/HttpClient/HttpClient.php(177): Gitlab\HttpClient\Listener\ErrorListener->postSend(Object(Gitlab\HttpClient\Message\Request), Object(Gitlab\HttpClient\Message\Response))
#1 /Users/john.milmine/Sites/gitlab_migration/vendor/m4tthumphrey/php-gitlab-api/lib/Gitlab/HttpClient/HttpClient.php(117): Gitlab\HttpClient\HttpClient->request('projects', Array, 'POST', Array)
#2 /Users/john.milmine/Sites/gitlab_migration/vendor/m4tthumphrey/php-gitlab-api/lib/Gitlab/Api/AbstractApi.php(63): Gitlab\HttpClient\HttpClient->post('projects', Array, Array)
#3 /Users/john.milmine/Sites/gitlab_migration/vendor/m4tthumphrey/php-gitlab-api/lib/Gitlab/Api/Projects.php(95): Gitlab\Api\AbstractApi->p in /Users/john.milmine/Sites/gitlab_migration/vendor/m4tthumphrey/php-gitlab-api/lib/Gitlab/HttpClient/Listener/ErrorListener.php on line 47

Fatal error: Uncaught exception 'Gitlab\Exception\ErrorException' with message '400 (Bad request) "name" not given' in /Users/john.milmine/Sites/gitlab_migration/vendor/m4tthumphrey/php-gitlab-api/lib/Gitlab/HttpClient/Listener/ErrorListener.php on line 47

Gitlab\Exception\ErrorException: 400 (Bad request) "name" not given in /Users/john.milmine/Sites/gitlab_migration/vendor/m4tthumphrey/php-gitlab-api/lib/Gitlab/HttpClient/Listener/ErrorListener.php on line 47
```

From code:
```
$newProject = \Gitlab\Model\Project::create($newGitlabClient, 'asd', array());
```

**Comment by m4tthumphrey** [comment]
Just had a scan through the code and the `name` param is definitely sent to Gitlab. so I'm wondering if `asd` is too short for a repo name...

**Comment by saschame** [comment]
Same here. Tried with a longer repo name: `abcdefghijklm`

PHP `5.6.8 (cli)`
GitLab `7.13.3`
GitLab `API v3`

```
PHP Fatal error:  Uncaught exception 'Gitlab\Exception\ErrorException' with message '400 (Bad request) "name" not given' in /www/dev/vendor/m4tthumphrey/php-gitlab-api/lib/Gitlab/HttpClient/Listener/ErrorListener.php:47
Stack trace:
#0 /www/dev/vendor/m4tthumphrey/php-gitlab-api/lib/Gitlab/HttpClient/HttpClient.php(177): Gitlab\HttpClient\Listener\ErrorListener->postSend(Object(Gitlab\HttpClient\Message\Request), Object(Gitlab\HttpClient\Message\Response))
#1 /www/dev/vendor/m4tthumphrey/php-gitlab-api/lib/Gitlab/HttpClient/HttpClient.php(117): Gitlab\HttpClient\HttpClient->request('projects', Array, 'POST', Array)
#2 /www/dev/vendor/m4tthumphrey/php-gitlab-api/lib/Gitlab/Api/AbstractApi.php(63): Gitlab\HttpClient\HttpClient->post('projects', Array, Array)
#3 /www/dev/vendor/m4tthumphrey/php-gitlab-api/lib/Gitlab/Api/Projects.php(95): Gitlab\Api\AbstractApi->post('projects', Array)
#4 /www/dev/ in /www/dev/vendor/m4tthumphrey/php-gitlab-api/lib/Gitlab/HttpClient/Listener/ErrorListener.php on line 47
```

**Comment by m4tthumphrey** [comment]
I've just run the same code as @pitchandtone..

`$newProject = \Gitlab\Model\Project::create($newGitlabClient, 'asd', array());`

and it created fine. But I am only on 7.12.2 so maybe something broke in 7.13?

**Comment by saschame** [comment]
probably 7.13.

How can I test/help?

**Comment by m4tthumphrey** [comment]
I'd suggest popping over to the [Gitlab project](https://github.com/gitlabhq/gitlabhq) and look around the issues and see anyone else has reported it... I'll be upgrading soon so I'll check it out.

**Comment by saschame** [comment]
I couldn't find any related issues on the Gitlab project. Will wait for you to upgrade.
If it is indeed a problem with 7.13, you're in a better position to pose an informed question and raise an issue.

**Comment by m4tthumphrey** [comment]
Just upgraded to 7.13.5 and it's still working fine. Can you maybe post some context of your app?

**Comment by saschame** [comment]
Found it!

My GitLab server is setup to redirect `http` requests to `https` and I connected through the php-gitlab-api via `http`:

```php
// wrong (http://)
$client = new \Gitlab\Client('http://gitlab.mydomain.com/api/v3/');

// correct  (https://)
$client = new \Gitlab\Client('https://gitlab.mydomain.com/api/v3/');
```

When using the php-gitlab-api to get projects or search, this redirection is working.
But when you send a `POST` request, to create a new user, the redirection seems to loose the data.

**Comment by m4tthumphrey** [comment]
Ah right! Probably todo with [this issue](https://github.com/kriswallsmith/Buzz/issues/140)

**Comment by chteuchteu** [comment]
Same issue here with the issues api:

    $client = new Client('http://gitlab.com/api/v3/');
    ...
    $client->api('issues')->create($project['id'], [
        'title' => 'Test',
        'description' => 'Test description'
    ]);

The code above will throw this error

> [Gitlab\Exception\ErrorException]
> 400 (Bad request) "title" not given

Switching from `http://gitlab.com/api/v3/` to `https://gitlab.com/api/v3/` does the trick.
This is definitely a mishandled redirection from buzz. Should we keep this issue open until buzz gets updated?

**Comment by m4tthumphrey** [comment]
@chteuchteu That Buzz issue is 3 years old so no we won't be relying on Buzz! Also there have been plans to move to Guzzle instead of Buzz so it will be a non-issue eventually.
