### ISSUE TITLE
Create project with namespace_id doesnt work

### ISSUE THREAD

**Issue by wallish** [m4tthumphrey/php-gitlab-api#105]
PHP `5.6.10 `
GitLab `7.12.2`
GitLab `API v3`

```php
$token = "xxxxxxx"
$client = new \Gitlab\Client('https://myrepo.foobar.fr/api/v3/');
$client->authenticate($token, \Gitlab\Client::AUTH_URL_TOKEN);

$result = $client->api('namespaces')->all();
// result contents
array(3) { 
    ["id"]=> int(20) 
    ["path"]=> string(6) "mygroup" 
    ["kind"]=> string(4) "group"
}

$client->api('projects')->create('test-foobar', [
    'namespace_id' =>  20,
    'description' => 'test'
]);
```

I get an errror : `"namespace" is not valid`.
Without the 'namespace_id' it work well.

**Comment by m4tthumphrey** [comment]
Without looking into it more I have a feeling that you may need to pass the path as the `namespace_id`, not the actual integer ID. As per your example:

```php
$client->api('projects')->create('test-foobar', [
    'namespace_id' =>  'mygroup',
    'description' => 'test'
]);
```

I may be wrong though...

**Comment by wallish** [comment]
I solved my problem, my user (from the token) hasn't the rights for create a project in the group `mygroup`.
And yes we have to use the group id, like this :
```php
$client->api('projects')->create('test-foobar', [
    'namespace_id' =>  20,
    'description' => 'test'
]);
```
I think we should display an appropriate error message when this problem is triggered

Thx for your help ;)
