### ISSUE TITLE
SearchMergeRequestsByIid

### ISSUE THREAD

**Issue by artkom911** [m4tthumphrey/php-gitlab-api#114]
Please, add in class MergeRequests extends AbstractApi
public method like

public function getByIid($project_id, $mr_iid)
{
    return $this->get($this->getProjectPath($project_id, 'merge_requests'), array('iid' => $mr_iid));
}

**Comment by m4tthumphrey** [comment]
Feel free to add it yourself! Try to add some tests with it too though!

**Comment by artkom911** [comment]
With pleasure! but I denied access to your repository.

**Comment by Zeichen32** [comment]
You can fork the repo and create a merge request. ;)

**Comment by artkom911** [comment]
I created a merge reguest https://github.com/m4tthumphrey/php-gitlab-api/pull/115, but there is an error when checking unrelated amended https://travis-ci.org/m4tthumphrey/php-gitlab-api/jobs/108891748. Checks on other versions of php successful https://travis-ci.org/m4tthumphrey/php-gitlab-api/builds/108891747. What are the next actions?

**Comment by m4tthumphrey** [comment]
I'm not sure why but theres something happening with OpenSSL on the 5.3.3 builds, don't worry about it, I've merged it!
