### ISSUE TITLE
How to install it via downloaded zip in wamp server.

### ISSUE THREAD

**Issue by rtplvaibhav** [m4tthumphrey/php-gitlab-api#117]
I have downloaded this api and extracted it in wamp server, but its not working. How to get it working on localhost wamp server.

**Comment by m4tthumphrey** [comment]
What is not working? How far have you got?

**Comment by rtplvaibhav** [comment]
Fatal error: Class 'Buzz\Client\Curl' not found in D:\wamp\www\gitlab\Gitlab\Client.php on line 78

This is the error, i am facing right now.

<?php
require_once(__DIR__ . '/Gitlab/Client.php');
$client = new \Gitlab\Client('http://git.yourdomain.com/api/v3/');
$client->authenticate('your_gitlab_token_here', \Gitlab\Client::AUTH_URL_TOKEN); // change here

$project = $client->api('projects')->create('My Project', array(
  'description' => 'This is a project',
  'issues_enabled' => false
));

This is my initial code

**Comment by m4tthumphrey** [comment]
You will need Composer for this project to work. Checkout [this tutorial](http://codezag.com/how-to-install-composer-wamp/) on install Composer on WAMP.

Once installed, run `composer install` in the project root and include `vendor/autoload.php` instead of `require_once(DIR . '/Gitlab/Client.php');`

And you should be good to go.

**Comment by rtplvaibhav** [comment]
Hi Matt,
I am now trying to install it via composer. Below is the error which i am facing right now.

D:\wamp\www\gitlab>composer install
You are running composer with xdebug enabled. This has a major impact on runtime
 performance. See https://getcomposer.org/xdebug
Loading composer repositories with package information
Installing dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package m4tthumphrey/php-gitlab-api No version set (parsed a
s 1.0.0) could not be found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your min
imum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more det
ails.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further commo
n problems.



And here is my composer.json code

{
	"name": "m4tthumphrey/php-gitlab-api",
	"type": "library",
	"description": "GitLab API client",
	"homepage": "https://github.com/m4tthumphrey/php-gitlab-api",
	"keywords": ["gitlab", "api"],
	"license": "MIT",
	"authors": [
		{
			"name": "Matt Humphrey",
			"homepage": "http://m4tt.io"
		},
		{
			"name": "KnpLabs Team",
			"homepage": "http://knplabs.com"
		},
		{
			"name": "Thibault Duplessis",
			"email": "thibault.duplessis@gmail.com",
			"homepage": "http://ornicar.github.com"
		}
	],
	"require": {
		"php":                ">=5.3.2",
		"ext-curl":           "*",
		"kriswallsmith/buzz": ">=0.7",
		"m4tthumphrey/php-gitlab-api": "dev-master"
	},
	"require-dev": {
		"phpunit/phpunit": "~4.5"
	},
	"autoload": {
		"psr-0": { "Gitlab\\": "lib/" }
	}
}

**Comment by m4tthumphrey** [comment]
All you need in your `composer.json` file is

```json
{
  "require": {
    "m4tthumphrey/php-gitlab-api": "dev-master"
  }
}
```

You will probably want to set a specific version based on your [Gitlab version](https://github.com/m4tthumphrey/php-gitlab-api#versioning).

**Comment by rtplvaibhav** [comment]
Hi Matt,
Now i managed to get it installed.
But dont know how to use it. Below is my code

<?php 
require_once '/vendor/autoload.php';

$client = new \Gitlab\Client('https://localhost/gitlab/api/v3/'); // change here
$client->authenticate('XYZ', \Gitlab\Client::AUTH_URL_TOKEN); // change here

#$project = $client->api('projects');
$project = $client;
echo '<pre>';print_r($project);
?>

 I have two queries here
1) What link should be given in $client = new \Gitlab\Client('https://localhost/gitlab/api/v3/'); // change here
2) How can i fetch the branches of a repo and its commits using this api as this is not given in the documentation? It would be better if you can provide any sample project code.

**Comment by m4tthumphrey** [comment]
[The API Guide](http://doc.gitlab.com/ce/api/) should help you out.
