### ISSUE TITLE
Not possible to create issues

### ISSUE THREAD

**Issue by larsemil** [m4tthumphrey/php-gitlab-api#119]
I am trying to create issues, but its not possible.

Using this code:
`$client->api('issues')->create(220, ['title' => 'Test', 'description' => 'test']);`

If I var_dump the $params in AbstractApi post method i do get a return like this:
```
array:2 [
  "title" => "Test"
  "description" => "test"
]

```
But still i get the response:
`Gitlab\Exception\ErrorException with message '400 (Bad request) "title" not given'`

**Comment by m4tthumphrey** [comment]
What version of Gitlab are you running?

**Comment by larsemil** [comment]
GitLab Community Edition 8.7.0 f2a3f70

**Comment by m4tthumphrey** [comment]
Hmm. The latest version of Gitlab I have access to is still on 7.13.5. I've had a quick through the changelog and cant see anything of note that would cause this. Does other parts of the API still work? Also can you try performing a raw request to the create issues endpoint and see if you get the same response?

**Comment by larsemil** [comment]
[](curl -k -X POST -H "PRIVATE-TOKEN: removed" https://gitlab.mydomain/api/v3/projects/220/issues?title=Testing_the_api)
Gives the response:
`{"id":1575,"iid":1,"project_id":220,"title":"Testing_the_api","description":null,"state":"opened","created_at":"2016-05-04T10:00:45.383Z","updated_at":"2016-05-04T10:00:45.383Z","labels":[],"milestone":null,"assignee":null,"author":{"name":"Emil Österlund","username":"larsemil","id":3,"state":"active","avatar_url":"https://secure.gravatar.com/avatar/4b2fad1cc8482becebf57d5407a2bbf5?s=80\u0026d=identicon","web_url":"https://gitlab.mydomain/u/larsemil"},"subscribed":true}`

**Comment by m4tthumphrey** [comment]
Can you try the client with the same title as your example?

**Comment by larsemil** [comment]
What do you mean?

**Comment by m4tthumphrey** [comment]
I want to eliminate the title being "Test" as the issue.

**Comment by larsemil** [comment]
Works with Test as title.
and test.

**Comment by m4tthumphrey** [comment]
Via the client?

**Comment by larsemil** [comment]
Actually that worked. :/ 
`GitLab::api('issues')->create(220, ['title' => 'This is a real title', 'description' => 'And a real description']);`

**Comment by m4tthumphrey** [comment]
Yeh thought so... I think this has come up before. Seems a bit odd but looks like it is Gitlab treating it as a fail.

**Comment by larsemil** [comment]
But now it works even if i put test as title. Well. Happy now. :)

**Comment by m4tthumphrey** [comment]
How strange, glad it's sorted! :)

**Comment by stephanvierkant** [comment]
I'm having the same problem while using Gitlab.com. 

> [Gitlab\Exception\ErrorException]
> 400 (Bad request) "title" not given

The raw request (mentioned above) works perfectly, but with the API client it doesn't.

**Comment by m4tthumphrey** [comment]
@stephanvierkant Can you paste the code?

**Comment by KoenRijpstra** [comment]
I got the error `title is missing` when using `http` instead of `https`

**Comment by Yousha** [comment]
I got the error `title is missing` when using `Content-Type` as `text/plain`, instead of `application/json` (in Postman)

**Comment by GrahamCampbell** [comment]
@Yousha If you upgrade to the latest version of this package, this issue and many others are resolved.
