### ISSUE TITLE
Missing support for build variables

### ISSUE THREAD

**Issue by ndubbaka** [m4tthumphrey/php-gitlab-api#127]
How to create & update variables using php-gitlab-api as provided by GitLab API?
http://doc.gitlab.com/ce/api/build_variables.html

**Comment by m4tthumphrey** [comment]
There is no native support for any of the CI methods but you could just create your own wrapper or just use the [`HttpClient`](https://github.com/m4tthumphrey/php-gitlab-api/blob/master/lib/Gitlab/HttpClient/HttpClient.php) class directly.

```php
$client = new HttpClient(/*..*/);
$client->get('/projects/1/triggers'); // etc
```

Feel free to submit a PR to provide this functionality if you wish 😄
