### ISSUE TITLE
Releases zip out of sync with source

### ISSUE THREAD

**Issue by benmag** [m4tthumphrey/php-gitlab-api#132]
Having a weird issue 

It seems like the release zip is out of sync with the actual code base. 

I don't mean no one has created a new release since the latest changes, I mean there were 30 or so commits in 7.3.0 and some more in 7.3.1 but those aren't in the release zips

For example 

There's a new method `build` in the Project API that were included in the 7.3.0 release but when you download the 7.3.0 zip and check the Api/Project.php it's not in there

**Comment by fbourigault** [comment]
Hello, is this issue still relevant?

**Comment by benmag** [comment]
I believe this issue fixed (itself?) with the recent releases
