### ISSUE TITLE
Add Deploy Key API Not working 

### ISSUE THREAD

**Issue by lukepolo** [m4tthumphrey/php-gitlab-api#135]
It seems the deploy key api function is broken 

`
"title" can't be blank, "title" is too short (minimum is 0 characters), "key" can't be blank, "key" is too short (minimum is 0 characters), "key" is invalid, "fingerprint" has already been taken, "fingerprint" cannot be generated`

on latest version hitting http://gitlab.com

**Comment by lukepolo** [comment]
#146 
Most likely solved my issue thanks!

**Comment by lukepolo** [comment]
Had to write it manually, it seems it must accept it as json 


```
  $client->post('https://gitlab.com/api/v3/projects/'.$repositoryInfo['id'].'/deploy_keys', [
                'Authorization' => 'Bearer tokenHere',
                'Content-Type' => 'application/json'
            ], [
                'title' => 'Some TItle ',
                'key' => $sshKey
            ])->send();
```

**Comment by Nyholm** [comment]
Do you have the same issue with late latest beta version?

**Comment by lukepolo** [comment]
Yup seems to be working
