### ISSUE TITLE
Add archive/unarchive.

### ISSUE THREAD

**Issue by Stefangemfind** [m4tthumphrey/php-gitlab-api#141]
Hello!

Can you guys add the ability to archive/unarchive a project?
API information here: http://docs.gitlab.com/ee/api/projects.html#archive-a-project

Stefan.

**Comment by radutopala** [comment]
@Stefangemfind done by @A-Lawrence in PR #142.

**Comment by Stefangemfind** [comment]
Fantastic! Thank you very very much!
