### ISSUE TITLE
Can not create Project in a Group

### ISSUE THREAD

**Issue by larsroettig** [m4tthumphrey/php-gitlab-api#145]
I can not create a new Project in Group test.
```
$name = "testModule";
$path = 'test';
$pathName =  $path."/".$name;

\Gitlab\Model\Group::create($gitLabClient, $path, $path);

// create a new project
\Gitlab\Model\Project::create(
    $gitLabClient, $name, array('name_with_namespace'=> $pathName,
                                'path_with_namespace' => $pathName,
                                'description' => $name)
);
```

**Comment by m4tthumphrey** [comment]
There seems to be issues within Gitlab when using `test` as the title or name of a project or group. See also #119

**Comment by AizeLeOuf** [comment]
You still can't created a project in group. Projects are created for current logged user trougth API. 

Please fix it and offer a createProjectForGroup.
Thanks,

**Comment by m1guelpf** [comment]
@AizeLeOuf PRs welcome
