### ISSUE TITLE
Projects search in Gitlab 8.11

### ISSUE THREAD

**Issue by radykal-com** [m4tthumphrey/php-gitlab-api#148]
Hello,

I'm just trying to use this library to connect to our 8.11 Gitlab instance and found, for example, the projects search method is not working, it works if change the request from /projects/search/.... to /projects?search=... like it is in other ones. 

I don't know if this change is needed for 8+ of Gitlab or it is just a bug also failing in previous versions.
If is a change required only for v8+ is there any plan on creating a new branch for v8 and release it?

I could help with it if needed.

Thanks you,

**Comment by fbourigault** [comment]
Hello, this is solved since [9.0.0-beta2](https://github.com/m4tthumphrey/php-gitlab-api/releases/tag/9.0.0-beta2) is out. This require to have at least Gitlab 9.0, but I hope you are up to date :)
