### ISSUE TITLE
Simple Question concerning pagination of project members

### ISSUE THREAD

**Issue by solcaj** [m4tthumphrey/php-gitlab-api#160]
GitLab API per default defines 20 items `per_page` for the returned result. Now if a project has more than 20 members we have an issue with increasing the number of items to _max_ i.e. 100. 

I tried different things since members can take an additional query but was not lucky so far. 

The call 
```
$gitlab_project_members = $client->api('projects')->members($repo_id)
```
So the question is how to navigate with the pagination or how to increase the `per_page` value ? 

Using GitLab 8.12.X version 

Thanks for your help

**Comment by m4tthumphrey** [comment]
Hey! We just need to add a few more arguments to the `members()` method.  Someone has [just started](https://github.com/psi-dev-group/php-gitlab-api/commit/524bf0d567e4a4754ede2a330bf5ee138642d07f) their own version of this so this gives you a rough idea of what needs to be done. 

I'll get to it eventually.

**Comment by solcaj** [comment]
Hey what a coincidence !!  this is exactly the patch I made for our fork.. We were not sure if to create a merge request was useful since not a lot of activities going on. our apologies and really glad you replied. Anyway waiting for the upcoming release ;-) and thanks for your work

**Comment by jinchun** [comment]
It hasn't been fixed yet.
