### ISSUE TITLE
Missing License Information

### ISSUE THREAD

**Issue by jboilesen** [m4tthumphrey/php-gitlab-api#161]
Hi @m4tthumphrey , how are you??

Hope you're doing fine. =)

I would love to use and contribute for this project but I am missing the license so I can align with my own projects.

Thnx!! =D

**Comment by glaubinix** [comment]
@jboilesen the license it set in the composer.json file.
https://github.com/m4tthumphrey/php-gitlab-api/blob/master/composer.json#L7
