### ISSUE TITLE
Create key missing title , missing key

### ISSUE THREAD

**Issue by lukepolo** [m4tthumphrey/php-gitlab-api#167]
When trying to create an ssh key im having this error

```
array:1 [▼
  "error" => "key is missing, title is missing"
]
```

```
$this->client->api('users')->createKey(
    $this->sshKeyLabel($site),
    $site->public_ssh_key
);
```

They are not empty, i checked. :-)

**Comment by m4tthumphrey** [comment]
Are you using `test` as the title? Seems to be [weird outcomes](https://github.com/m4tthumphrey/php-gitlab-api/issues/119).

**Comment by lukepolo** [comment]
Nope, I just did a request myself and seemed to work

**Comment by m4tthumphrey** [comment]
So theres no issue?

**Comment by lukepolo** [comment]
No i wrote it like : 

```
 $client->post('https://gitlab.com/api/v3/projects/'.$repositoryInfo['id'].'/deploy_keys', [
            'Authorization' => 'Bearer '.$site->userRepositoryProvider->token,
            'Content-Type' => 'application/json',
        ], [
            'title' => 'CodePier',
            'key' => $site->public_ssh_key,
        ])->send();
```

Because it did not work through the package

**Comment by m4tthumphrey** [comment]
I just did a quick test using the following

```php
$gitlab = new Client('https://mygitlab.com/');
$gitlab->authenticate('...');

$gitlab->api('users')->createKey(
    'test',
    '...'
);`

And it worked fine but I am running 7.13.5 so maybe something has changed in later versions. I can't why what you just posted would work using the client directly and not via the package though...

**Comment by m4tthumphrey** [comment]
Just noticed the content type.. it could well be todo with later versions requiring JSON input on specific methods?

**Comment by fbourigault** [comment]
I tried this with 9.1.0 and it's working fine on gitlab.com.
Feel free to re-open this issue if issue is still valid for you.
Regards

**Comment by Yousha** [comment]
Same error when using package `php-http/socket-client` as `psr/http-client-implementation` .

Fixed by using package `kriswallsmith/buzz` instead.

**Comment by GrahamCampbell** [comment]
@Yousha If you upgrade to the latest version of this package, this issue and many others are resolved.

**Comment by Yousha** [comment]
@GrahamCampbell Already using latest version, but it wasn't about the version.
