### ISSUE TITLE
createFile method not working

### ISSUE THREAD

**Issue by drupalninja** [m4tthumphrey/php-gitlab-api#168]
Getting error:
{"error":"file_path is missing, branch_name is missing, commit_message is missing, content is missing"}

I am using syntax $project->createFile('file1', 'contents', 'master', 'file');

So far I have $project->getFile() working so I am not sure if this is a bug or like a permissions problem?

**Comment by m4tthumphrey** [comment]
There is definitely something strange happening at the moment as we seem to getting a lot of reports todo with missing arguments when they are present. Are you using gitlab.com or self hosted?

**Comment by drupalninja** [comment]
I am using gitlab.com, thanks for responding so quick! I have tried even using the post method to call the same thing more directly but I get the same errors. I have a suspicion that it's some kind of permission where I am not being allowed to push commits but then the error I am getting doesn't seem to indicate that at all.

$parameters = ['file_path' => 'app/project.rb', 'content' => 'contents', 'branch_name'=> 'master', 'commit_message' => 'file', 'author_email' => 'author@example.com', 'author_name' => 'FirstnameLastname', 'encoding' => 'text'];
  $file = $client->getHttpClient()->post('projects/2405100/repository/files', $parameters);

**Comment by m4tthumphrey** [comment]
That error message is coming directly from gitlab.com not from the client so I guess there is an issue with the error reporting within Gitlab?

**Comment by drupalninja** [comment]
I am using the personal key not the oauth token if that matters. The examples here show the secret key being passed in.

https://docs.gitlab.com/ce/api/repository_files.html

**Comment by drupalninja** [comment]
Re: "That error message is coming directly from gitlab.com not from the client so I guess there is an issue with the error reporting within Gitlab?" correct I keep trying to see if I am just doing something wrong with the syntax I am using but it seems to line up with the documentation.

**Comment by drupalninja** [comment]
The error code is '400 Bad Request'

**Comment by drupalninja** [comment]
If the commit fails for any reason we return a 400 error with a non-specific error message. Possible causes for a failed commit include:

the file_path contained /../ (attempted directory traversal);
the new file contents were identical to the current file contents, i.e. the user tried to make an empty commit;
the branch was updated by a Git push while the file edit was in progress.

**Comment by drupalninja** [comment]
I am going to try postman in Chrome to see if I can get it to work there

**Comment by m4tthumphrey** [comment]
This method isn't the only time we've seen problems with this sort of error. #167 #135 

Although looking at #135 I wonder if it's because of the content type... I'll do some investigating, in the meantime when you try it in Postman can you use both JSON and encoded form as the content types and see what happens.

**Comment by drupalninja** [comment]
<img width="732" alt="screen shot 2017-01-31 at 9 51 46 am" src="https://cloud.githubusercontent.com/assets/1112449/22472349/f2782cee-e79a-11e6-852b-60a590031163.png">

Using XHR POSTER I tried doing a POST with the Contnt type 'application/json' which now renders a blank 400 which is interesting. I am not sure my syntax is correct.

**Comment by drupalninja** [comment]
Also if it matters I am using the '\Gitlab\Client::AUTH_URL_TOKEN' authentication method when using the PHP API

**Comment by m4tthumphrey** [comment]
Hmm it could do, try the `AUTH_HTTP_TOKEN` method. Also your JSON isn't valid in that screen shot, the quotes should be `"` not `'`. Not sure if your client will auto convert but its worth making sure the JSON is valid.

**Comment by drupalninja** [comment]
![screen shot 2017-01-31 at 10 17 57 am](https://cloud.githubusercontent.com/assets/1112449/22473443/8f0ab5ce-e79e-11e6-8203-3880c41a481a.png)

Awesome it looks like it worked after fixing a few things, that's progress

**Comment by drupalninja** [comment]
Would it be wise to update the createFile method to submit parameters as json?

**Comment by drupalninja** [comment]
I tried AUTH_HTTP_TOKEN but that didn't work - am I supposed to just pass the private key as the first parameter?

**Comment by drupalninja** [comment]
Just for reference I did a normal PHP curl request bc I couldn't figure out how to hack the API to send as JSON. This did work so my thinking is that once the PHP API is updated to send params as JSON, it will work.

$parameters = ['file_path' => 'asdasdasd', 'content' => 'contents asdasd', 'branch_name'=> 'master', 'commit_message' => 'file', 'author_email' => 'author@example.com', 'author_name' => 'FirstnameLastname'];
  //$file = $client->getHttpClient()->post('projects/2405100/repository/files', $parameters);

  // Setup cURL
  $ch = curl_init('https://gitlab.com/api/v3/projects/2405100/repository/files');
  curl_setopt_array($ch, array(
    CURLOPT_POST => TRUE,
    CURLOPT_RETURNTRANSFER => TRUE,
    CURLOPT_HTTPHEADER => array(
      'PRIVATE-TOKEN:' . $token,
      'Content-Type: application/json'
    ),
    CURLOPT_POSTFIELDS => json_encode($parameters)
  ));

  // Send the request
  $response = curl_exec($ch);

**Comment by m4tthumphrey** [comment]
Someone must've changed in the Gitlab API code at some point for the regular input to be ignored now. I will do some tests and see if changing the content type to JSON across the board will have any other consequences.

**Comment by fbourigault** [comment]
Could you test if this issue is solved by #241?
