### ISSUE TITLE
Gitlab API v4

### ISSUE THREAD

**Issue by bdandoy** [m4tthumphrey/php-gitlab-api#171]
https://about.gitlab.com/2017/02/22/gitlab-8-17-released/ With v4 in beta and set to be released on 3/22 is their any current plans on how to update this project to use the new api?

**Comment by m4tthumphrey** [comment]
Hey @bdandoy!

I'll be honest and say that I was not aware of v4 until right now! There are no concrete "plans" so far but I will be looking into the changes between v3 and v4 personally today. 

We are actually working on an internal tool based around Gitlab in my day job so I would imagine we would be revisiting this heavily in the coming months.

This is a great opportunity to look at a full rewrite utilising modern PHP as discussed in #54, #55 and #50 including switching from Buzz to Guzzle.

**Comment by curry684** [comment]
I just processed a similar upgrade in https://github.com/omines/oauth2-gitlab/issues/1, please keep in mind that current roadmap schedules v3 to be *removed* in Gitlab 9.4, due July 22nd.

**Comment by fbourigault** [comment]
Consider moving to php-http/httplug instead of guzzle :)

**Comment by m4tthumphrey** [comment]
@fbourigault why? What's the difference?

**Comment by Nyholm** [comment]
The major difference is that HTTPlug is an abstraction and Guzzle is an implementation. If we go with an abstraction we let our users decide what HTTP client to use. One clear benefit from this is that users stuck with Guzzle5 can still use this library. Also, we do not have to bother when Guzzle bumps to version 7. 

Some major projects that have chosen HTTPlug is KNPlabs github API and PHP Geocoder.

Disclaimer: I am part of the php-http team and we are currently maintaining Guzzle.

**Comment by fbourigault** [comment]
@m4tthumphrey I just found that #50 is already about using php-http/httplug. Are you still ok with that?

**Comment by lordao** [comment]
Is anyone still working on this? GitLab plans disabling v3 by version 9.3, which should come by June 22.

**Comment by m4tthumphrey** [comment]
@lordao I cannot commit enough time to this migrating to v4. Anyone who feels like they would like to take it on just let me know and I can add you to the project.

**Comment by fbourigault** [comment]
> I just found that #50 is already about using php-http/httplug. Are you still ok with that?

ping @m4tthumphrey

**Comment by m4tthumphrey** [comment]
@fbourigault Yes I don't see why not. As long as Guzzle users can still use it, which if I understand correctly, they can with httplug

**Comment by fbourigault** [comment]
Yes, httplug has an adapter for all popular http clients out into the wild!

**Comment by curry684** [comment]
Deprecation date updated @ https://docs.gitlab.com/ce/api/v3_to_v4.html:

> API V3 will be removed in GitLab 9.5, to be released on August 22, 2017.

@m4tthumphrey does this help you to update the package in time?

**Comment by fbourigault** [comment]
I'm starting to work about replacing buzz with httplug. Should I keep the code BC?

**Comment by curry684** [comment]
It's going to be breaking anyway to switch to v4. I would recommend skipping to PHP 5.6 in one go anyway to follow PHP's own EOL policies @ http://php.net/supported-versions.php

**Comment by fbourigault** [comment]
Does everyone agrees with:
- moving to httplug (#191)
- moving to PSR-4 (#55)
- using autoload-dev instead of https://github.com/m4tthumphrey/php-gitlab-api/blob/master/test/bootstrap.php
- support only PHP 5.6+

We also must create a new branch from the current master to keep a v3 compatible branch.

**Comment by Nyholm** [comment]
Many libraries I work with are dropping php5.6 support when bumping to a major version. It may be something we also want to consider here. 

👍

**Comment by curry684** [comment]
If 7+ features are not required or of true added value I wouldn't do it yet as 5.6 will still be supported for 1.5 year. Symfony 4 can make the break to 7.1 because they will still support 3.4 (5.3+ compatible!) until november 2020 (!).

So unless someone is willing to maintain the current branches for those stuck on PHP 5 for some time, which is far from unlikely in enterprise applications that would include a library like this, I'd stick with 5.6.

I'll also be happy to do some of the work, just don't have tons of time for it and I'll want to make sure someone's going to be reviewing and merging.

**Comment by fbourigault** [comment]
V4 API support is now in master. See https://github.com/m4tthumphrey/php-gitlab-api/issues/200#issuecomment-319335801 for a probable release planning.
