### ISSUE TITLE
Request for collaborators

### ISSUE THREAD

**Issue by m1guelpf** [m4tthumphrey/php-gitlab-api#192]
Hi!
This project seems a little abandoned, looking at the commits after latest tag, pull requests open (and I mean **finished** pull requests) and number of issues open.
To @m4tthumphrey:
- Do you still mantain this?
- Who has push access?

If you are to busy to work on this, maybe you should assign some mantainers...

@m4tthumphrey edit:

If you wish to help maintain this project, please let me know here and I will invite to collaborate.

**Comment by m4tthumphrey** [comment]
I do not have time to work on it at present but hope to get back on to it eventually. I have offered to assign more maintainers several times. It would seem no one has put their names forward recently.

**Comment by m4tthumphrey** [comment]
cc @fbourigault @gimler @donkidd

**Comment by fbourigault** [comment]
I can spent some time on this library. As you can see, I'm working on moving out of Buzz #191. After that I will work on v4 api compatibility (unless someone else does).

**Comment by m4tthumphrey** [comment]
Thanks @fbourigault I have just invited you.

**Comment by m1guelpf** [comment]
@m4tthumphrey I would also like to help, probably with issues, PR and maybe adding or reviewing endpoints, or adding missing docblocks :smile:

**Comment by donkidd** [comment]
@m4tthumphrey  I'd be willing to help as well.  I was wanting to add some tests but hadn't gotten to it yet

**Comment by fbourigault** [comment]
@m4tthumphrey thanks for the invitation. How do you mind my collaboration on this repository?

**Comment by m1guelpf** [comment]
ping @m4tthumprey again

**Comment by m4tthumphrey** [comment]
Sorry for delay @m1guelpf, just sent you an invite! Thanks for getting involved!

**Comment by fbourigault** [comment]
Do we need more contributors? We are now two active maintainers.

**Comment by m4tthumphrey** [comment]
@fbourigault No probably not, we can close this!
