### ISSUE TITLE
StyleCI

### ISSUE THREAD

**Issue by m1guelpf** [m4tthumphrey/php-gitlab-api#194]
Hi!
I see they aren't any CS Style fixers in this project.
May I recommend using StyleCI to have a consistent style on the project?
Thank you!

**Comment by fbourigault** [comment]
Ping @m4tthumphrey!

**Comment by m4tthumphrey** [comment]
By all means!

**Comment by fbourigault** [comment]
Could you enable it?

**Comment by m4tthumphrey** [comment]
What do I need todo?

**Comment by fbourigault** [comment]
First, you can go on https://styleci.io, login with your Github account, clic on your username on the top right corner, go in the repo tab and hit the enable styleci button for this repository.

Then IIRC, we will be able to configure styleci using a file in this repository. You can also disable email notifications if you don't want to get annoyed with failing analysis!

**Comment by m4tthumphrey** [comment]
[![StyleCI](https://styleci.io/repos/6816335/shield?branch=master)](https://styleci.io/repos/6816335)

```
[![StyleCI](https://styleci.io/repos/6816335/shield?branch=master)](https://styleci.io/repos/6816335)
```

If you need any settings changed let me know.

**Comment by fbourigault** [comment]
Thank you! IIRC, all config can be done using a `.styleci.yml` file.

**Comment by fbourigault** [comment]
Before applying fixes to get the build green, which preset should we apply?
Here is the list: https://styleci.readme.io/docs/presets

I used to use the `symfony` preset with the `short_array_syntax` fixer.

**Comment by m4tthumphrey** [comment]
I dont mind which preset, whatever the general consensus is! If it's just a file within the repo that needs to be added, feel free to do so!

**Comment by fbourigault** [comment]
I will use the psr-2 preset as it's the php-fig standard.
