### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by m4tthumphrey** [m4tthumphrey/php-gitlab-api#2]

**Comment by m4tthumphrey** [comment]
Have also created a new `tests` branch, am starting with the Api classes. Going to take a while I reckon!

**Comment by m4tthumphrey** [comment]
Projects, Groups and Namespaces all done.

**Comment by m4tthumphrey** [comment]
Users, Milestones, Groups, Snippets, SystemHooks

**Comment by m4tthumphrey** [comment]
Repositories, Issues, Merge Requests all done.

**Comment by m4tthumphrey** [comment]
Whole of `Gitlab\Api` is now under test.

**Comment by m4tthumphrey** [comment]
Test comment

**Comment by glensc** [comment]
this looks stale and should be closed

**Comment by GrahamCampbell** [comment]
Thanks @glensc. :)
