### ISSUE TITLE
Move to V4 API.

### ISSUE THREAD

**Issue by fbourigault** [m4tthumphrey/php-gitlab-api#200]
Gitlab V3 api will be removed in 9.5 release (22th august).

From https://docs.gitlab.com/ce/api/v3_to_v4.html, I listed all breaking changes in the API. All those changes does not affect us but we have to double check!!!

So if anyone could look into the code and tell if we are affected or not, I would be happy to tick boxes. If we are affected, feel free to open PRs to fix it.

cc @m1guelpf

### 8.17

- [x] Removed `GET /projects/:search` (use: `GET /projects?search=x`) [!8877](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/8877)
- [x] `iid` filter has been removed from `GET /projects/:id/issues` [!8967](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/8967)
- [x] `GET /projects/:id/merge_requests?iid[]=x&iid[]=y` array filter has been renamed to `iids` [!8793](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/8793)
- [x] Endpoints under `GET /projects/merge_request/:id` have been removed (use: `GET /projects/merge_requests/:id`) [!8793](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/8793)
- [x] Project snippets do not return deprecated field `expires_at` [!8723](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/8723)
- [x] Endpoints under `GET /projects/:id/keys` have been removed (use `GET /projects/:id/deploy_keys`) [!8716](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/8716)

### 9.0

- [x] Status 409 returned for `POST /projects/:id/members` when a member already exists [!9093](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/9093)
- [x] Moved `DELETE /projects/:id/star` to `POST /projects/:id/unstar` [!9328](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/9328)
- [x] Removed the following deprecated Templates endpoints (these are still accessible with `/templates` prefix) [!8853](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/8853)
  - [x] `/licences`
  - [x] `/licences/:key`
  - [x] `/gitignores`
  - [x] `/gitlab_ci_ymls`
  - [x] `/dockerfiles`
  - [x] `/gitignores/:key`
  - [x] `/gitlab_ci_ymls/:key`
  - [x] `/dockerfiles/:key`
- [x] Moved `POST /projects/fork/:id` to `POST /projects/:id/fork` [!8940](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/8940)
- [x] Moved `DELETE /todos` to `POST /todos/mark_as_done` and `DELETE /todos/:todo_id` to `POST /todos/:todo_id/mark_as_done` [!9410](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/9410)
- [x] Project filters are no longer available as `GET /projects/foo`, but as `GET /projects?foo=true` instead [!8962](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/8962)
  - [x] `GET /projects/visible` & `GET /projects/all` are consolidated into `GET /projects` and can be used with or without authorization
  - [x] `GET /projects/owned` moved to `GET /projects?owned=true`
  - [x] `GET /projects/starred` moved to `GET /projects?starred=true`
- [x] `GET /projects` returns all projects visible to current user, even if the user is not a member [!9674](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/9674)
  - [x] To get projects the user is a member of, use `GET /projects?membership=true`
- [x] Return pagination headers for all endpoints that return an array [!8606](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/8606)
- [x] Added `POST /environments/:environment_id/stop` to stop an environment [!8808](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/8808)
- [x] Removed `DELETE /projects/:id/deploy_keys/:key_id/disable`. Use `DELETE /projects/:id/deploy_keys/:key_id` instead [!9366](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/9366)
- [x] Moved `PUT /users/:id/(block|unblock)` to `POST /users/:id/(block|unblock)` [!9371](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/9371)
- [x] Make subscription API more RESTful. Use `POST /projects/:id/:subscribable_type/:subscribable_id/subscribe` to subscribe and `POST /projects/:id/:subscribable_type/:subscribable_id/unsubscribe` to unsubscribe from a resource. [!9325](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/9325)
- [x] Labels filter on `GET /projects/:id/issues` and `GET /issues` now matches only issues containing all labels (i.e.: Logical AND, not OR) [!8849](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/8849)
- [x] Renamed param `branch_name` to `branch` on the following endpoints [!8936](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/8936)
  - [x] `POST /projects/:id/repository/branches`
  - [x] `POST /projects/:id/repository/commits`
  - [x] `POST/PUT/DELETE :id/repository/files`
- [x] Renamed the `merge_when_build_succeeds` parameter to `merge_when_pipeline_succeeds` on the following endpoints: [!9335](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/)
  - [x] `PUT /projects/:id/merge_requests/:merge_request_id/merge`
  - [x] `POST /projects/:id/merge_requests/:merge_request_id/cancel_merge_when_pipeline_succeeds`
  - [x] `POST /projects`
  - [x] `POST /projects/user/:user_id`
  - [x] `PUT /projects/:id`
- [x] Renamed `branch_name` to `branch` on `DELETE /projects/:id/repository/branches/:branch` response [!8936](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/8936)
- [x] Remove `public` param from create and edit actions of projects [!8736](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/8736)
- [x] Remove `subscribed` field from responses returning list of issues or merge
  requests. Fetch individual issues or merge requests to obtain the value
  of `subscribed`
  [!9661](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/9661)
- [x] Use `visibility` as string parameter everywhere [!9337](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/9337)
- [x] Notes do not return deprecated field `upvote` and `downvote` [!9384](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/9384)
- [x] Return HTTP status code `400` for all validation errors when creating or updating a member instead of sometimes `422` error. [!9523](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/9523)
- [x] Remove `GET /groups/owned`. Use `GET /groups?owned=true` instead [!9505](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/9505)
- [x] Return 202 with JSON body on async removals on V4 API (`DELETE /projects/:id/repository/merged_branches` and `DELETE /projects/:id`) [!9449](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/9449)
- [x] `GET /projects/:id/milestones?iid[]=x&iid[]=y` array filter has been renamed to `iids` [!9096](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/9096)
- [x] Return basic info about pipeline in `GET /projects/:id/pipelines` [!8875](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/8875)
- [x] Renamed all `build` references to `job` [!9463](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/9463)
- [x] Drop `GET /projects/:id/repository/commits/:sha/jobs` [!9463](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/9463)
- [x] Rename Build Triggers to be Pipeline Triggers API [!9713](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/9713)
  - [x] `POST /projects/:id/trigger/builds` to `POST /projects/:id/trigger/pipeline`
  - [x] Require description when creating a new trigger `POST /projects/:id/triggers`
- [x] Simplify project payload exposed on Environment endpoints [!9675](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/9675)
- [x] API uses merge request `IID`s (internal ID, as in the web UI) rather than `ID`s. This affects the merge requests, award emoji, todos, and time tracking APIs. [!9530](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/9530)
- [x] API uses issue `IID`s (internal ID, as in the web UI) rather than `ID`s. This affects the issues, award emoji, todos, and time tracking APIs. [!9530](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/9530)
- [x] Change initial page from `0` to `1` on `GET /projects/:id/repository/commits` (like on the rest of the API) [!9679](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/9679)
- [x] Return correct `Link` header data for `GET /projects/:id/repository/commits` [!9679](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/9679)
- [x] Update endpoints for repository files [!9637](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/9637)
  - [x] Moved `GET /projects/:id/repository/files?file_path=:file_path` to `GET /projects/:id/repository/files/:file_path` (`:file_path` should be URL-encoded)
  - [x] `GET /projects/:id/repository/blobs/:sha` now returns JSON attributes for the blob identified by `:sha`, instead of finding the commit identified by `:sha` and returning the raw content of the blob in that commit identified by the required `?filepath=:filepath`
  - [x] Moved `GET /projects/:id/repository/commits/:sha/blob?file_path=:file_path`  and `GET /projects/:id/repository/blobs/:sha?file_path=:file_path` to `GET /projects/:id/repository/files/:file_path/raw?ref=:sha`
  - [x] `GET /projects/:id/repository/tree` parameter `ref_name` has been renamed to `ref` for consistency
- [x] `confirm` parameter for `POST /users` has been deprecated in favor of `skip_confirmation` parameter

**Comment by m4tthumphrey** [comment]
Wow! Thank you so much for taking this on! 🙇

**Comment by fbourigault** [comment]
As this list may be hard to user, I think we should do a PR per gitlab merge request which introduced the change.

You can find changes for https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/8936 in #205.

**Comment by fbourigault** [comment]
We are not affected by https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/9328 changes.

**Comment by fbourigault** [comment]
I'm working on changes affecting the `GET /projects` endpoint. Do we agree using the Symfony OptionsResolver component to handle nicely [all available options](https://docs.gitlab.com/ee/api/projects.html#list-projects)?

This will enable strong input validation and will help to keep code clean (i.e. avoid [code like this](https://github.com/m4tthumphrey/php-gitlab-api/blob/6cc26a0f59785f5a81f85eca65f5e43adf5588a6/lib/Gitlab/Api/Issues.php#L16-L20)).

**Comment by m1guelpf** [comment]
@fbourigault :+1:

**Comment by fbourigault** [comment]
You can have a look of how the code is when using `OptionsResolver`: https://github.com/m4tthumphrey/php-gitlab-api/compare/master...fbourigault:options-resolver

**Comment by m1guelpf** [comment]
@fbourigault Cleaner. I like it.

**Comment by fbourigault** [comment]
Some people suggested me to not using the `$definition` array as it looks like a code offuscation. I updated the diff and it looks better to me.

**Comment by fbourigault** [comment]
You can find changes for for [!8962](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/8962), [!8877](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/8877) and [9674](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/9674) in #213.

**Comment by fbourigault** [comment]
Everything have been merged.

I will release a beta by the end of this week. From 5th to 12th, I will be offline.
Then I hope enough people will have test this first beta and if there are regressions, a 2nd beta could be released around the 17th. Then I plan to release a RC around the 21th and a stable by the end of the month.

Because of the really short delay until https://gitlab.com v3 API get shutdown, I think this is fair compromise!
