### ISSUE TITLE
How to post more files?

### ISSUE THREAD

**Issue by AntoninSlejska** [m4tthumphrey/php-gitlab-api#209]
I use the following method for posting more files to Gitlab: https://github.com/AntoninSlejska/php-gitlab-api/blob/8.0.1/lib/Gitlab/Api/Repositories.php#L369
The array $actions contains one or more objects: https://github.com/AntoninSlejska/php-gitlab-api/blob/8.0/docs/actions-array.txt

Is it possible to use for posting of more files some of the existing methods?

**Comment by fbourigault** [comment]
Not yet. There is an [existing pull request](https://github.com/m4tthumphrey/php-gitlab-api/pull/158) but it has to be rebased.

**Comment by AntoninSlejska** [comment]
Thanks @fbourigault 
Is there any chance, that the pull request will be rebased and accepted in the near future?

**Comment by fbourigault** [comment]
I just notified the PR author about required rebase. As changes required are important (related to [HTTPlug](http://httplug.io/), feel free to open an other PR. I will be happy to review it!

**Comment by AntoninSlejska** [comment]
If the author will not react, then I try to open other PR. Thanks.

**Comment by Nyholm** [comment]
It seams like you can open a PR. =)

**Comment by AntoninSlejska** [comment]
OK. I have to finish a project at first. Then I will open the PR.

**Comment by AntoninSlejska** [comment]
I try to send the following POST request to Gitlab:

```
PAYLOAD=$(cat << 'JSON'
{
  "branch": "master",
  "commit_message": "some commit message",
  "actions": [
    {
      "action": "create",
      "file_path": "foo/bar",
      "content": "some content"
    },
    {
      "action": "delete",
      "file_path": "foo/bar2"
    }
  ]
}
JSON
)
curl --request POST --header "PRIVATE-TOKEN: 9koXpg98eAheJpvBs5tK" --header "Content-Type: application/json" --data "$PAYLOAD" https://gitlab.example.com/api/v4/projects/1/repository/commits
```

See: https://docs.gitlab.com/ce/api/commits.html#create-a-commit-with-multiple-files-and-actions

I suppose the method 'actions' should look like this:

    /**
     * @param int $project_id
     * @param array $actions
     * @param string $branch
     * @param string $commit_message
     * @param string $encoding
     * @return mixed
     */
    public function actions($project_id, array $actions, $branch, $commit_message)
    {
        return $this->post($this->getProjectPath($project_id, 'repository/commits'), array(
            'branch' => $branch,
            'commit_message' => $commit_message,
            'actions' => $actions,
        ));
    }

But I get the following error message:

> Gitlab\Exception\ErrorException: Unknown action ''
in /var/www/my-site/vendor/m4tthumphrey/php-gitlab-api/lib/Gitlab/HttpClient/Plugin/GitlabExceptionThrower.php:32

The array in the variable $actions looks like:

	Array
	(
	[branch] => master
	[commit_message] => some commit message
	[actions] => Array
		(
		[0] => Array
			(
			[action] => create
			[file_path] => foo/bar
			[content] => some content
			)
		[1] => Array
			(
			[action] => delete
			[file_path] => foo/bar2
			)
		)
	)

Have you any idea, what do I make wrong?
