### ISSUE TITLE
a typo

### ISSUE THREAD

**Issue by Baclic** [m4tthumphrey/php-gitlab-api#219]
a typo in the file 

>/m4tthumphrey/php-gitlab-api/lib/Gitlab/Api/MergeRequests.php

in method "show", (91):

Now : 

> return $this->get($this->getProjectPath($project_id, 'merge_request/'.$this->encodePath($mr_id)));

Need:

> return $this->get($this->getProjectPath($project_id, 'merge_request**S**/'.$this->encodePath($mr_id)));

**Comment by m1guelpf** [comment]
@Baclic This is intentional, we are migrating to the v4 API. See #200.
