### ISSUE TITLE
The server does not see the parameters passed in the request body (Updated)

### ISSUE THREAD

**Issue by Baclic** [m4tthumphrey/php-gitlab-api#220]
Hello. 
Week ago i create ticket 

> https://github.com/m4tthumphrey/php-gitlab-api/issues/204

Now, in last version, POST-request has been fixed, but PUT-request still don't see the variables passed in the body (for exampe, i can't change password from user), as before

**Comment by fbourigault** [comment]
Hello, thank you for reporting this issue. Could you test with https://github.com/fbourigault/php-gitlab-api/tree/issue-220?
