### ISSUE TITLE
updateFile not working

### ISSUE THREAD

**Issue by heximcz** [m4tthumphrey/php-gitlab-api#239]
HI,

I have a problem with migrate from v3 to v4. 
updateFile get error:
```
[Gitlab\Exception\RuntimeException]  
  404 Not Found
```

Same error for createFile method.

Code:
```
$project = new Project($this->getProjectID(), $this->client);
$project->updateFile($filePath, $content, $branch, $message);
```
Create new project, getFile working fine.

I use:

```
GitLab 9.5.1
GitLab Shell 5.8.0
GitLab Workhorse v3.0.0
GitLab API v4
Git 2.13.5
Ruby 2.3.3p222
Rails 4.2.8
postgresql 9.6.3 
```

**Comment by fbourigault** [comment]
Thank you for reporting this bug. The `Gitlab\Api\Repositories` `createFile`, `updateFile` and `deleteFile` methods have not been updated for V4 API.

Feel free to open a PR for fixing those methods.

**Comment by heximcz** [comment]
Ok I have a solution:

**./Model/Project.php**
- createFile and updateFile - add parameter $encoding
- $author_email and $author_name can't be null in url 

**./Api/Repositories.php**
- createFile and updateFile add : (Url encoded full path to new file. Ex. lib%2Fclass%2Erb)
```
...$this->getProjectPath($project_id, 'repository/files/'.$file_path)...
```
- delete 'file_path' => $file_path from array
- check if author and email is not null
- check if encoding is base64 (if yes add 'encoding' => 'base64' to the array)
- no one parameter in url (array) can't be null !

Voila it's working.

[api create/update file doc](https://docs.gitlab.com/ee/api/repository_files.html)

Can you fix this ASAP ?

**Comment by fbourigault** [comment]
Could you test if #241 solve this issue?

**Comment by heximcz** [comment]
Solved. I tested create and update file.

**Comment by fbourigault** [comment]
I just published 9.2.0 which include #241 changes.

**Comment by heximcz** [comment]
Thank you. But can you fixed getFile in ./Model/Project.php too ? Fix please names of parameters and call you new method repositoryFiles()->getFile....

**Comment by fbourigault** [comment]
Parameters are the same for backward compatibility but the new code is used instead.
