### ISSUE TITLE
Following SemVer

### ISSUE THREAD

**Issue by m1guelpf** [m4tthumphrey/php-gitlab-api#246]
Just as a suggestion, how about following SemVer from now?

**Comment by fbourigault** [comment]
That's already what I am doing :)

**Comment by m1guelpf** [comment]
@fbourigault SemVer states you should release on every change. As far as I know, we are not doing that.

**Comment by fbourigault** [comment]
I don't think semver is about when to release. It's just about major/minor/bugfix. I think I'm releasing quite often and if it's not enough, I'm tagging releases on-demand!

**Comment by m1guelpf** [comment]
Yeah, you're right. Closing this.
