### ISSUE TITLE
Define Coding Standard in the Readme

### ISSUE THREAD

**Issue by c33s** [m4tthumphrey/php-gitlab-api#252]
just a suggestion: 

maybe it would be a good idea to expose the coding standard of this project in the `README.md`. 

of course keen eyes can find it in the `.styleci.yml` but also writing it down in the `README.md` and maybe add some info about how to check it offline would be an improvement. 

offline check
```
wget https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/download/v2.6.0/php-cs-fixer.phar -O php-cs-fixer
php php-cs-fixer.phar fix ./ --rules=@PSR2 --dry-run
```

adding a local config file for the cs fixer would also be possible

`.php_cs.dist`
```
$finder = PhpCsFixer\Finder::create()
    ->exclude('vendor')
    ->in(__DIR__)
;

return PhpCsFixer\Config::create()
    ->setRules([
        '@PSR2' => true,
    ])
    ->setFinder($finder)
;
```

then you can run 
```
php php-cs-fixer.phar fix --dry-run
```

i can do a PR if you would accept this suggestion

**Comment by m1guelpf** [comment]
@c33s In my opinion, the developers don't actually need to submit Pull Request in the same code style as the repo, as StyleCI can get that autofixed for us, so I don't believe this is neccesary. @m4tthumphrey What do you think?

**Comment by 20uf** [comment]
I find that the proposal @c33s is interesting, seeing an interest of a pre-commit that verifies that the rules of style are respected before push.

The interest is that developers know style code to apply and to avoid making changes in a second time, this can be avoided simply as well.

**Comment by m1guelpf** [comment]
@20uf As I said before, there's no need to make any code style changes, as StyleCI should auto-solve the issues if there are any on the master branch.

**Comment by c33s** [comment]
@m1guelpf it is just a help for the interested developer. so he or she can learn the new coding style.

**Comment by fbourigault** [comment]
I'm for adding a note into the `README.md` but not for adding a `.phpcs.dist` file to the repository. This is just to help developers and not used in any ci task.

**Comment by GrahamCampbell** [comment]
I've added contribution guide for clarity. I've also enabled a lot more rules, taking us to a standard very close to Symfony's.
