### ISSUE TITLE
Problem with updating an issue

### ISSUE THREAD

**Issue by phsteffen** [m4tthumphrey/php-gitlab-api#254]
Hi Folks,

i found a little Bug in the issue-upate-function:

https://github.com/m4tthumphrey/php-gitlab-api/blob/70aeb9f412f8dc184dbd91afd75058ab8702746e/lib/Gitlab/Model/Issue.php#L94

To Update the issue the gitlab-api needs the `iid` and not the `id` of the issue.  
[Link to the api-doc](https://docs.gitlab.com/ee/api/issues.html#edit-issue)

I think it should be:  
`$data = $this->client->issues()->update($this->project->id, $this->iid, $params);`

**Comment by phsteffen** [comment]
Same thing here:

https://github.com/m4tthumphrey/php-gitlab-api/blob/70aeb9f412f8dc184dbd91afd75058ab8702746e/lib/Gitlab/Model/Issue.php#L83

I think this should be work:

`$data = $this->client->issues()->show($this->project->id, $this->iid);`

**Comment by m1guelpf** [comment]
@phsteffen Can you open a PR?

**Comment by phsteffen** [comment]
@m1guelpf PR is open: https://github.com/m4tthumphrey/php-gitlab-api/pull/255
Thx.
