### ISSUE TITLE
Create project in namespace

### ISSUE THREAD

**Issue by topdown** [m4tthumphrey/php-gitlab-api#26]
Is it possible to create a project in a namespace with your wrapper?
I don't see how to set the namespace ID.

I did find this https://groups.google.com/forum/#!topic/gitlabhq/x7MOmJGWLSc
So it is possible with the API, was scratching my head because it wasn't in the API documentation either.

**Comment by zanematthew** [comment]
Could you provide a code snippet on using this one? Its not that clear for me as others you can interact with like the following:

`$project = $client->api('projects')->create('My Project', ... `

I tried: `$client->api('projectnamespaces')->all()`, which I'm sure is wrong, and doesn't work.

**Comment by zanematthew** [comment]
Dug deeper and found this: `$client->api('namespaces')->all();`
