### ISSUE TITLE
Branches containing a slash break v4 branch endpoints

### ISSUE THREAD

**Issue by vetruvet** [m4tthumphrey/php-gitlab-api#263]
The encoding of branch names in API v4 has changed from unencoded slashes to encoded as "%2f". As such, getting branch information for a branch like "env/production" is broken in the latest version.

Ironically this means #86 basically needs to be reverted.

Removing the `str_replace` call in [Repositories](https://github.com/m4tthumphrey/php-gitlab-api/blob/master/lib/Gitlab/Api/Repositories.php#L432) fixes the issue for me but I'm not sure if there are any other places where this needs to be done.

**Comment by fbourigault** [comment]
Could you open a PR to fix this? If we find other places later we will do more fixes.
