### ISSUE TITLE
Requirement not found

### ISSUE THREAD

**Issue by brandon-welsch** [m4tthumphrey/php-gitlab-api#271]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - m4tthumphrey/php-gitlab-api 9.5.0 requires php-http/client-implementation ^1.0 -> no matching package found.
    - m4tthumphrey/php-gitlab-api 9.4.0 requires php-http/client-implementation ^1.0 -> no matching package found.
    - m4tthumphrey/php-gitlab-api 9.3.0 requires php-http/client-implementation ^1.0 -> no matching package found.
    - m4tthumphrey/php-gitlab-api 9.2.0 requires php-http/client-implementation ^1.0 -> no matching package found.
    - m4tthumphrey/php-gitlab-api 9.1.0 requires php-http/client-implementation ^1.0 -> no matching package found.
    - m4tthumphrey/php-gitlab-api 9.0.0 requires php-http/client-implementation ^1.0 -> no matching package found.

**Comment by fbourigault** [comment]
As this library is decoupled from any http client implementation, you have to choose one. You can read the [installation](https://github.com/m4tthumphrey/php-gitlab-api#installation) paragraph of the readme to help you choosing an implementation.
