### ISSUE TITLE
Dependency no more available: php-http/client-implementation

### ISSUE THREAD

**Issue by smalot** [m4tthumphrey/php-gitlab-api#295]
The `php-http/client-implementation` is no more available, so the library can't be installed.

Any solution ?

Thanks for all

**Comment by m1guelpf** [comment]
@fbourigault Any ideas?

**Comment by fbourigault** [comment]
The pho-http/client-implementation is a virtual package. You have to install a client or an adapter which provide the implementation. You can read the installation section of this repository readme.

**Comment by smalot** [comment]
Thanks !

**Comment by smalot** [comment]
I suppose Guzzle can do the job ?
