### ISSUE TITLE
kriswallsmith/buzz 0.17 not compatible with 8.0

### ISSUE THREAD

**Issue by frankvanrest** [m4tthumphrey/php-gitlab-api#308]
We get the error:

```
Error: Uncaught exception 'Error' with message 'Call to undefined method Buzz\Client\Curl::setTimeout()' in /www/vendors/vendor/m4tthumphrey/php-gitlab-api/lib/Gitlab/Client.php:79
```

We solved it by adding 0.16.1 explicitly to our composer.json:

```
        "m4tthumphrey/php-gitlab-api":"~8",
        "kriswallsmith/buzz":"0.16.1",
```

**Comment by iltar** [comment]
Ran into this issue as well. According to semver, the `0.*` releases can contain BC breaks, which sadly broke my application. I think the `kriswallsmith/buzz` dependency should be tighter.
