### ISSUE TITLE
Document that Issues::all() does not in fact return all issues due to pagination

### ISSUE THREAD

**Issue by ijks** [m4tthumphrey/php-gitlab-api#319]
The GitLab API normally limits the list of issues to 100 entries per request, with a default of 20. This means that `Issues::all()` and `Project::issues()` by extension only return the first 20 issues of a project by default, which is surprising given their respective names. It'd be nice if the docs stated this fact, and provided a workaround.

I'd be willing to write a PR for this.

**Comment by andersruneson** [comment]
Is there a work around for fetching more then 20 right now? I think I have the same problem fetching more projects with this code:
`
$pager = new \Gitlab\ResultPager($client);
$projects = $pager->fetchall($client->api('projects'),'all',[[]]);
`


> Make sure to set per_page (default: 20, max: 100 as per docs here) in the initial request to desired value (I prefer 100) to get the correct value for X-Total-Pages.

@fr0z3nfyr  How?

**Comment by fr0z3nfyr** [comment]
@andersruneson this particular issue is about fetching list of issues on a project. Your code sample suggests you are trying to fetch list of projects. 

Refer to the official docs [here](https://docs.gitlab.com/ce/api/projects.html#list-all-projects) which nowhere suggests that the list of projects will be limited to 20. Also, from the docs:

> Get a list of all visible projects across GitLab for the authenticated user. When accessed without authentication, only public projects are returned.

Are you sure your authenticated user has access to more than 20 projects on the gitlab server?

**Comment by andersruneson** [comment]
@fr0z3nfyr Right, I'm trying to fetch projects and thought it was related. I get exactly 40 projects for the above code. The user can access all projects. If I create a new project, that project is listed but the total is still 40 since another project did not list anymore.

**Comment by andersruneson** [comment]
@mzeis Can't remember exactly, but I think I do longer use the script which needed to fetch all projects. But I'm also having trouble with pagination with other api calls like fetching jobs etc.

**Comment by andersruneson** [comment]
@mzeis @fr0z3nfyr 
I accidentally had this issue again while writing another script. I had the exact same issue as you @mzeis that it worked fine on one system but not on the other. The strange this is they are both running the same version of PHP 7.2.24-0ubuntu0.18.04.3!
I got some more details this time, I think something is really borked with the pagination. Adding the parameter per_page 20 gave a result of 40 projects, per_page=25 gave 50. So the pagination only doubles the amount of results!

**Comment by akondas** [comment]
I have exactly the same situation, on one machine the same organization returns 81 projects, and on another only 40, regardless of everything. Did someone find anything?

**Comment by akondas** [comment]
Hello my friends :wink: I was able to reproduce it. Everything is guilty of the `Link` header in the response. 

When requests are sent from the PHP version without support for the `curl` extension, php cuts this header (I don't know why). Installing curl and using it (for example, via `CurlHttpClient`) solves all problems.

**Comment by akondas** [comment]
Protip: try to install `curl` extension first.

**Comment by dmclark** [comment]
@GrahamCampbell sorry for commenting on a closed issue, but it relates to my question.

I checked & confirmed that curl in enabled in php (7.4) but for the life of me I don't know how  CurlHttpClient and/or access the x-vars in the response header.

My code is:
`$gl = new \Gitlab\Client();
$gl->setUrl($url);
$gl->authenticate($token, Gitlab\Client::AUTH_OAUTH_TOKEN);
$projs = $gl->projects(['orderBy'=> 'last_activty_date','sort'=>'desc','per_page'=>'100'])->all();
`

(It took me forever to realize that $params went to projects() and not. all() as I read the code)

Sorry to be such a NOOB

**Comment by GrahamCampbell** [comment]
You should use the result pager. It should never be necessary to manually set per page or page numbers. :)

**Comment by GrahamCampbell** [comment]
https://github.com/GitLabPHP/Client#example-with-pager

**Comment by dmclark** [comment]
Thanks so much @GrahamCampbell 

Whenever I add parameters, like

$projs = $pager->fetchAll($client->projects(),'all', ['orderBy'=> 'last_activty_date']); 


I get a 500 error  with no info in error logs

**Comment by GrahamCampbell** [comment]
The last param there looks incorrect. That needs to be an array of parameters to pass. You need `[['orderBy'=> 'last_activty_date']]` instead of `['orderBy'=> 'last_activty_date']`.

**Comment by dmclark** [comment]
hmm.. 

$projs = $pager->fetchAll($client->projects(),'all', [['orderBy'=> 'last_activty_date']]);


same thing

**Comment by GrahamCampbell** [comment]
Maybe your server is running out of memory? Not much else I can suggest here.

**Comment by dmclark** [comment]
My apologies for being an idiot.

In case It helps anybody ellse
'orderBy'=> 'last_activty_date'
should be
'order_by' => 'last_activity_at',
