### ISSUE TITLE
[question] Self-signed certificate

### ISSUE THREAD

**Issue by mbraun81** [m4tthumphrey/php-gitlab-api#350]
If i try to connect to my gitlab host i get an PHP Fatal error:

> Uncaught GuzzleHttp\Exception\RequestException: cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.h                               axx.se/libcurl/c/libcurl-errors.html) in ...vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:186

How can i set the $options['verify'] to false in the httpClient to use my self-signed cert?

**Comment by blackfyre** [comment]
I'm also interested in this!

**Comment by m1guelpf** [comment]
Feel free to submit a PR to tweak this!

**Comment by GrahamCampbell** [comment]
This can be customised in the usual way by passing an http client to the http builder.

**Comment by GregKapustin** [comment]
You may also use [curl info ca cert](https://curl.haxx.se/ca/cacert.pem) in your php ini, worked for me

**Comment by betz** [comment]
> This can be customised in the usual way by passing an http client to the http builder.

could you give an example on how to achieve this?

**Comment by grasmash** [comment]
```
use Gitlab\Client;
use Gitlab\HttpClient\Builder;

$client = new Client(new Builder(new \GuzzleHttp\Client(['verify' => FALSE])));
```
