### ISSUE TITLE
Only 20 results are returned

### ISSUE THREAD

**Issue by abayob** [m4tthumphrey/php-gitlab-api#361]
Hello,

First of all, great library, very detailed and easy to use.

I was wondering, is there a way to return more than 20 results using this API?

```php
$api = \Gitlab\Client::createWithHttpClient($guzzle)
          ->setUrl($config->getUrl())
    	  ->authenticate($Config->getAccessToken(), \Gitlab\Client::AUTH_URL_TOKEN);
$tags = $api->tags()->all($projectID);
```

This sadly returns only 20 tags, I want to return more than 20 if possible.

The only way I know how, using your library, is manually adding the following in the `Tags` class:

```php
public function all($project_id, $perPage = 20)
{
    return $this->get($this->getProjectPath($project_id, 'repository/tags') , ['per_page'=> $perPage]);
}
```

Of course, I would not like to manually add anything, because I cannot update the package anymore without losing my changes.

Any work-around for this or maybe something to add in the future?

**Comment by cebe** [comment]
it is explained in the readme: https://github.com/m4tthumphrey/php-gitlab-api#example-with-pager

**Comment by Santana1053** [comment]
I'm also having this issue using the pager. I tried debugging the pager to see where it's failing, and it seems like the pager is looking for the `Link` header in the response, which doesn't seem to exist.
I'm not sure if the GitLab API updated, but the response headers that seem to provide the correct information are `X-Page`, `X-Next-Page` and `X-Total-Pages`

![image](https://user-images.githubusercontent.com/10775656/52437392-6b20e380-2adc-11e9-93a4-e3223be87b53.png)

**Comment by Santana1053** [comment]
I am also having this issue while using the pager. I attempted to debug the pager and discovered that it's looking for a response header `Link`, but that header doesn't exist. The correct headers to use should be 
```
X-Next-Page
X-Page
X-Per-Page
X-Runtime
X-Total
X-Total-Pages
```

**Comment by HighCoData** [comment]
We are not able to get the last page with the pager. We have to order our projects descending dates in order to get the latest projects. But otherwise all projects located in the last page are not retrieved.

**Comment by soullivaneuh** [comment]
@cebe The example does not work for some api ressource like projects, see:

https://github.com/nexylan/gitlab-report/blob/9373baa487e1c2432c38263ea991ce441f7f355a/src/Console/Command/ReportCommand.php#L50-L57

Only the 40 first projects are returned, nothing else.

**Comment by hguerrier** [comment]
I am also experiencing this. We are only able to return a limited number at a time.

**Comment by akondas** [comment]
Probably related with #319.

**Comment by akondas** [comment]
Protip: try to install `curl` extension :wink:
