### ISSUE TITLE
Error when installing using composer on PHP 7.3

### ISSUE THREAD

**Issue by Nikschavan** [m4tthumphrey/php-gitlab-api#384]
[ErrorException]
  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?

![image](https://user-images.githubusercontent.com/2931091/49996974-69dcaa00-ffb6-11e8-9e25-262be0620c8f.png)

**Comment by curry684** [comment]
Considering a `composer require` runs no code of the library being installed by default I'm suspecting your Composer version is severely outdated and in need of a `sudo composer self-update`.
