### ISSUE TITLE
9.12.0 not appearing on Packagist

### ISSUE THREAD

**Issue by drumm** [m4tthumphrey/php-gitlab-api#399]
https://packagist.org/packages/m4tthumphrey/php-gitlab-api does not have https://github.com/m4tthumphrey/php-gitlab-api/releases/tag/9.12.0 yet.

GitHub changed how hooks need to be implemented, which kicked in at the end of January. https://twitter.com/packagist/status/1037035587453235201

Thanks for tagging the release!

**Comment by m1guelpf** [comment]
cc @m4tthumphrey could you set up the GitHub app or transfer me the repo?

**Comment by m4tthumphrey** [comment]
I'll sort it tomorrow @m1guelpf

**Comment by m4tthumphrey** [comment]
Think I've sorted it @m1guelpf
