### ISSUE TITLE
Can't create issues

### ISSUE THREAD

**Issue by jboilesen** [m4tthumphrey/php-gitlab-api#414]
$project->createIssue() fails  with the following message:

"Message: Argument 3 passed to Gitlab\Model\Issue::fromArray() must be of the type array, string given, called in /vendor/m4tthumphrey/php-gitlab-api/lib/Gitlab/Model/Project.php on line 806"

**Comment by Crazynx** [comment]
Hey there, I fixed this issue by adding another pair of brackets around the parameters. I hope this works for you too!
Example:
Instead of `['id' => 1]` being your parameters, change it to `[['id' => 1]].
