### ISSUE TITLE
Specify gitlab port

### ISSUE THREAD

**Issue by mdemori** [m4tthumphrey/php-gitlab-api#417]
Hi, 

how can I specify the http port? I already tried with below code with no luck:

```
$gitLabUrl = 'http://test.me:4000/'; // tested both with final slash that without
$apiKey = 'my_api_key';

 $client = \Gitlab\Client::create($gitLabURL) ->authenticate($apiKey, \Gitlab\Client::AUTH_URL_TOKEN);
    
 $pager = new \Gitlab\ResultPager($client);
 $issues = $pager->fetchAll($client->api('issues'),'all',[null, ['state' => 'closed']]);

```
the generated URL miss the port so return an exception:

The requested URL /api/v4/issues was not found on this server.

after digging around i found that the url has been created as below:

http://test.me/api/v4/projects/

without the port so is not valid for my setup

**Comment by GrahamCampbell** [comment]
Thanks for the report. Were you able to look into debugging this?

**Comment by GrahamCampbell** [comment]
I am not able to replicate this. It is possible your choice of PSR-17 URI factory implementation has a bug.
