### ISSUE TITLE
GroupMilestone Model missing

### ISSUE THREAD

**Issue by B8Y** [m4tthumphrey/php-gitlab-api#427]
Hi,
with #390 the GroupsMilestones routes was added for the issue #389 but not the associated model.
Currently the Milestone model is bound to the project but in certain context we need these milestones to be bound to the group.
Given that I need this for a project I can make the PR and submit to your approval if you're ok with that.

**Comment by m1guelpf** [comment]
Feel free to PR this

**Comment by B8Y** [comment]
Thanks :)
