### ISSUE TITLE
phpstan failure

### ISSUE THREAD

**Issue by webmaster777** [m4tthumphrey/php-gitlab-api#471]
Gonna merge it and try to take care of the static analysis later

_Originally posted by @m1guelpf in https://github.com/m4tthumphrey/php-gitlab-api/pull/453#issuecomment-550231397_

The issue flagged by phpstan is real and should be addressed. Maintaining a version of this library that supports 2 versions of the same library is *hard*. However, if you do want to support both versions of HTTPlug (v1 and v2), you should make phpstan be able to live with that. Either add an exception to the phpstan config, or maintain 2 versions of the library (one for httplug:^1.6, one for httplug:^2.0). 

Ignoring a failing build (considering phpstan to be a valid step in the build process) is a red flag. Either you care about the messages or you don't. Ignoring it only makes it harder for others to contribute, since they will have to ignore it too, when contributing. This makes it harder to identify real issues with new contributions.

**Comment by webmaster777** [comment]
Or better yet, let phpstan anlayze the code without `COMPOSER_FLAGS="--prefer-lowest"`

**Comment by m1guelpf** [comment]
I'm closing this now, lemme know if this should be reopened
