### ISSUE TITLE
example please

### ISSUE THREAD

**Issue by thawkins** [m4tthumphrey/php-gitlab-api#480]
I cant seem to work out how to read objects/entities with this library.

There are dozens of examples of how to create things, but none on how to retrieve an entity. or even how to search for something.

Can somebody provide a simple snippet on how to find/retrieve a user with a given username or email-address. 

Thanks in anticipation...

**Comment by glensc** [comment]
@thawkins for starters, point to API documentation what you want to do, and show you obtained the same data with curl (gitlab API docs use curl examples), then I could perhaps help, otherwise, it's too vague effort.

**Comment by thawkins** [comment]
Sorry i resolved this,  its was a catestropic  comprehension failure.  You can close this one, however a few examples on how to query dsta would have helped.

**Comment by glensc** [comment]
@thawkins no, I can not close this. I'm not member of this project. but you can you are the original reporter.
