### ISSUE TITLE
improve library move to guzzle 4 out of buzz

### ISSUE THREAD

**Issue by cordoval** [m4tthumphrey/php-gitlab-api#49]
previous: https://github.com/m4tthumphrey/php-gitlab-api/issues/32

The library uses buzz introducing yet another dep in gush. We can move it to guzzle 4 which is suit. In addition we should start semver also bugfixes so we can change https://github.com/gushphp/gush-gitlab-adapter/blob/master/composer.json#L5 which is a mistake on the version this should require.

Gitlab support works more or less, I have tried it before. Not sure if there were things that worked differently or need more support. So if we have request please let us open tickets on gush-gitlab-adapter /cc @matthiasnoback

**Comment by m4tthumphrey** [comment]
Closing, please see #50
