### ISSUE TITLE
Retrieving variables of existing pipelines?

### ISSUE THREAD

**Issue by arnegroskurth** [m4tthumphrey/php-gitlab-api#514]
Am I missing something here is this this currently not supported?

https://docs.gitlab.com/ee/api/pipelines.html#get-variables-of-a-pipeline

**Comment by GrahamCampbell** [comment]
Yeh, I think you are correct that this is not implemented (yet). We'd happily accept a PR with tests to the 2.18 branch. :)

**Comment by arnegroskurth** [comment]
resolved by #526
