### ISSUE TITLE
tag 6.10

### ISSUE THREAD

**Issue by digitalkaoz** [m4tthumphrey/php-gitlab-api#53]
could you please tag a new stable release? to be able to use e.g. `MergeRequest::opened` and rely on stable versions

**Comment by m4tthumphrey** [comment]
There will not be a major new tag until the HTTP adaptor (#5, #50, #49), PHP version (#54) and PSR-4 (#55) discussions are concluded. I will also be doing a lot of house keeping over the coming days and weeks, which may include several breaking changes, mainly todo with models (#8, #10). I am not sure on the roadmap of Gitlab but envisage this to coincide with the release of 8.0 depending on @randx and co's plans.

However, I will tag a smaller release to coincide with the release of 7.8 next week.
