### ISSUE TITLE
PHP Version support

### ISSUE THREAD

**Issue by ls12styler** [m4tthumphrey/php-gitlab-api#54]
What should be the minimum supported version of PHP? Considering 5.3 was released over 5 years ago and that 5.6 was recently released, I would suggest the library targets no less that 5.5.

**Comment by m4tthumphrey** [comment]
I am thinking of going ahead with making the library PHP 5.4+ in the next major update

- Guzzle4 requires 5.4
- It's 2015
Thoughts? @ls12styler @hollodotme @jubianchi

**Comment by ls12styler** [comment]
Anything is better than 5.3 :) so thumbs up from me.

**Comment by m4tthumphrey** [comment]
Wow, glad we didn't switch to Guzzle4 as Guzzle is now on 6.2!

**Comment by fbourigault** [comment]
I'm closing this issue as 9.0 will ne PHP 5.6+. See #195.
