### ISSUE TITLE
PSR-4

### ISSUE THREAD

**Issue by ls12styler** [m4tthumphrey/php-gitlab-api#55]
http://www.php-fig.org/psr/psr-4/

This enables us to have a VendorName\PackageName namespace. I would suggest "php-gitlab-api\php-gitlab-api" as the vendor\package names. this may be better suited then in a GitHub organisation.
It would also allow the code structure to be a little bit neater.

It would also make the suggested adapter packages a little neater and easier to find.

Thoughts?

**Comment by m4tthumphrey** [comment]
I am thinking of going ahead with making the library PHP 5.4+ in the next major update 

- Guzzle4 requires 5.4
- It's 2015

Thoughts? @ls12styler @hollodotme @jubianchi @cordova

**Comment by fbourigault** [comment]
In #195, I changed the autoload config to use PSR-4 instead of deprecated PSR-0. I don't think changing namespace is a good idea as it's an heavy breaking change with near to 0 added value. What do you think about closing this issue?

**Comment by Nyholm** [comment]
:+1: for closing.
