### ISSUE TITLE
[RFC] Drop models API

### ISSUE THREAD

**Issue by GrahamCampbell** [m4tthumphrey/php-gitlab-api#554]
It's hard to keep up-dated. Unless someone wants to volunteer to spend a lot of time going through all of the models code updating it, maybe we should remove the models entirely?

**Comment by fbourigault** [comment]
What do you suggest? Using php arrays?

**Comment by GrahamCampbell** [comment]
@fbourigault No. To explain what I mean a little more. The design of this package is that we have a bunch of classes in `Gitlab/Api`. These talk to GitLab, and can be used in their own right. Most people using this package will probably be using that code. Importantly, this code is totally independent of the `Gitlab/Models` namespace, so that stuff could be removed, without effecting the function of the rest of the package.

The `Gitlab/Models` namespace is meant to provide an OOP-style wrapper for the APIs, however it has not been well maintained, and is a lot of work to work out which things are missing and/or incorrectly implemented.

NB The bitbucket and github api packages referenced in the readme don't implement models. We are the outlier here.

**Comment by GrahamCampbell** [comment]
If we do decide to remove them, I'd suggest we wait until 11.0 to do it, as to avoid hurting adoption of 10.0. We can leave them in and mark them as deprecated. There's no rush to remove them, just so long as we make it clear that they are deprecated.

**Comment by m4tthumphrey** [comment]
I would definitely agree in removing them. They were first introduced because that's how I was consuming the API in the beginning. Probably worth deprecating in the next release.

**Comment by GrahamCampbell** [comment]
I think I will aim to remove them in 11.0 (which will be released in 2021 or 2022 I guess). I don't wanna do it in 10.0 because it might stop people upgrading from 9.x to 10.x. We need to give people lots of notice.

**Comment by GrahamCampbell** [comment]
My current plan is to release 10.0.0 later this month, simultaneously with 9.19.0. Note also that 9.18.0 was tagged today, with lots of deprecations.

**Comment by glensc** [comment]
What about graphql? they wrote that they added it and support parallel with rest api. and just yesterday I noticed the gitlab website itself makes graphql queries.

- https://docs.gitlab.com/ee/api/graphql/
- https://docs.gitlab.com/ee/api/graphql/#vision
- https://docs.gitlab.com/ee/development/fe_guide/graphql.html

**Comment by GrahamCampbell** [comment]
I don't think graphql is right for the use cases of most people, certainly not for my use of the API. I am certainly not in supporting of implementing it here. I'd recommend creating an entirely new package for consuming their graphql api.

**Comment by GrahamCampbell** [comment]
Graphql has many disadvantages compared to standard HTTP APIs if you just want to use them as a REST API.

**Comment by m4tthumphrey** [comment]
Yeah this package is specifically for supporting the REST API. The model part of this lib was a superfluous addition that I included in the repo rather than in my app all those years ago. Nothing todo with the API itself, REST or GraphQL.

**Comment by GrahamCampbell** [comment]
Deprecating models in 10.1.0, for removal in 11.0.0. 10.1.0 will be released today. 11.0.0 will be some time in 2021, maybe in the summer.

**Comment by DBLaci** [comment]
I understand the concept of differentiating this project (as an API wrapper) and the models, but I prefer using objects and properties instead of simple associative arrays. In my project I override these models sometimes, but forcing the developers to implement all these models individually is not a great aproach. Maybe these Model classes could be moved to a different project then, for those (like me) likes to use the advantages of model objects.
