### ISSUE TITLE
Set name and path on fork project

### ISSUE THREAD

**Issue by S1933** [m4tthumphrey/php-gitlab-api#559]
Hi guys,

I'm trying to fork my project with name and path passed on parameters but variables don't are doesn't set on my new repository.

`$params = [
      "namespace" => $group,
      "name" => $name,
      "path" => $path
    ];
` 

`$this->client->projects()->fork($projectFork, $params);` 

Maybe, I used the wrong way to build my $params variable?

**Comment by GrahamCampbell** [comment]
The available parameters are documented at https://docs.gitlab.com/ee/api/projects.html#fork-project. If these are not working, then I'd recommend contacting GitLab's support.

**Comment by GrahamCampbell** [comment]
I don't think GitLab support passing all 3 of those at once btw?
