### ISSUE TITLE
ErrorListener does not support message array

### ISSUE THREAD

**Issue by Maff-** [m4tthumphrey/php-gitlab-api#56]
The `Gitlab\HttpClient\Listener\ErrorListener` will produce a Fatal error (_Wrong parameters for ErrorException_) when the Gitlab API returns a error message that contains an array instead of a string message. Offending line: [46][1]

```json
{"message":{"path":["has already been taken"]}}
```

This will mostly happen when an data validation error occurs. See [Data validation and error reporting](http://doc.gitlab.com/ce/api/README.html#data-validation-and-error-reporting) for possible response formats.

A simple solution could be to json encode the message when it's not a string.

[1]: https://github.com/m4tthumphrey/php-gitlab-api/blob/4168b2d297c8554f96a9baff99d1d5cc16cf8b90/lib/Gitlab/HttpClient/Listener/ErrorListener.php#L46

Used versions: GitLab 7.4.0; GitLab API v3

**Comment by j0k3r** [comment]
Any news about that issue ?

Still got some `Wrong parameters for Exception([string $exception [, long $code [, Exception $previous = NULL]]])`

Shouldn't just cast the `$errorMessage` ?

```php
throw new RuntimeException((string) $errorMessage, $response->getStatusCode());
```

**Comment by Maff-** [comment]
I think simply casting it to a string will just throw a _Array to string conversion_ notice. Not really a solution imo.

**Comment by jubianchi** [comment]
Hello folks!

I'm working on a patch right now, sorry for the delay I was really busy.
Hopefully I'll submit it today.

**Comment by m4tthumphrey** [comment]
Lots of ways of handling this...

- Convert the array to a JSON encoded string of the array
- Implode the list of errors with a comma (or any other char really)
- Grab the first error (preferred)

**Comment by j0k3r** [comment]
> Implode the list of errors with a comma (or any other char really)

:+1: 

So this error :
```
{
    "message": {
        "bio": [
            "is too long (maximum is 255 characters)"
        ],
        "path": [
            "has already been taken"
        ]
    }
}
```
should generate this exception message:
```
"bio" is too long (maximum is 255 characters), "path" has already been taken
```

I prefer to see all informations at once instead of getting the first error, fixin it, retryin, getting the second error (which I've not seen the first time since only the first error is reported), etc ..

**Comment by m4tthumphrey** [comment]
@j0k3r Yeh I agree. @jubianchi have you done anything on this yet? If not I'll do it now.. lemme know.

**Comment by m4tthumphrey** [comment]
I'm inpatient :wink:

**Comment by j0k3r** [comment]
@m4tthumphrey thanks !

Could you tag a new release then?

**Comment by jubianchi** [comment]
@m4tthumphrey I was about to do the same thing you did in your patch: parse the JSON containing error messages and format them as a comma separated list of errors.

:+1: thanks for the patch :)

**Comment by m4tthumphrey** [comment]
@j0k3r I'm working on a few clean up updates, once thats done I'll tag a new release.

**Comment by j0k3r** [comment]
@m4tthumphrey It seems to not be *fully* fixed, I just got :

> [app] exception 'Gitlab\Exception\RuntimeException' with message '"0" Array' in /vendor/m4tthumphrey/php-gitlab-api/lib/Gitlab/HttpClient/Listener/ErrorListener.php:60

I guess [`parseMessage`](https://github.com/m4tthumphrey/php-gitlab-api/blob/master/lib/Gitlab/HttpClient/Listener/ErrorListener.php#L68) needs a recursive function to handle the `$message`.

I'm running Gitlab 7.8.2.

**Comment by m4tthumphrey** [comment]
@j0k3r Do you what the Gitlab error was that caused it?

**Comment by j0k3r** [comment]
Sadly not.

**Comment by m4tthumphrey** [comment]
What were you trying to do when you had it?

**Comment by j0k3r** [comment]
It's hard to say because we have integrated your Gitlab API inside an internal project that rely on Git to store some config file. This error was reported to us by a user that use this project, so hard to say. I could be a commit, a push or a merge request creation.

I can give you first lines of the stacktrace:

```
#0 /vendor/m4tthumphrey/php-gitlab-api/lib/Gitlab/HttpClient/HttpClient.php(177): Gitlab\HttpClient\Listener\ErrorListener->postSend(Object(Gitlab\HttpClient\Message\Request), Object(Gitlab\HttpClient\Message\Response)) 
#1 /vendor/m4tthumphrey/php-gitlab-api/lib/Gitlab/HttpClient/HttpClient.php(117): Gitlab\HttpClient\HttpClient->request('projects/351/me...', Array, 'POST', Array) 
#2 /vendor/m4tthumphrey/php-gitlab-api/lib/Gitlab/Api/AbstractApi.php(62): Gitlab\HttpClient\HttpClient->post('projects/351/me...', Array, Array) 
```

**Comment by m4tthumphrey** [comment]
Looks like merge request creation... 

> `post('projects/351/me...'`

I'll take a look.

**Comment by m4tthumphrey** [comment]
Should be sorted; there was an obvious bug with the 3rd param of the sprintf but that doesn't account for the field being `"0"` so have checked for the presence of a field name.

**Comment by j0k3r** [comment]
Sounds good to me :+1:
