### ISSUE TITLE
Unable to retrieve groups by path in v10

### ISSUE THREAD

**Issue by ederuiter** [m4tthumphrey/php-gitlab-api#570]
In v10 parameter type hints were added to the Groups class; this prevents us from retrieving groups by path (https://docs.gitlab.com/ee/api/groups.html#details-of-a-group). 

For projects and repositories the id parameter has no typehint, I think the same has to be done for Groups.

https://github.com/GitLabPHP/Client/blob/10.0/src/Api/Groups.php#L38

(this does not only affect the show function, but also all other functions in Groups.php accepting an id)

If you want I can create a PR for this.

**Comment by GrahamCampbell** [comment]
I don't the Gitlab's API officially supports using the path? Could you link me to something in the docs that says the path can be used?

**Comment by ederuiter** [comment]
According to the docs it is supported, for example see https://docs.gitlab.com/ee/api/groups.html#details-of-a-group
```
id => integer/string => The ID or URL-encoded path of the group owned by the authenticated user.
```

Looking at the documentation for the other group api endpoints; all of them support it, with the exception of `update`. But that might just be a documentation issue.

**Comment by GrahamCampbell** [comment]
Right, so this actually needs to be fixed on 9.19, and then merged up into 10.0. Are you able to send a PR to correct the types in 9.19?

**Comment by MacTwister** [comment]
Is there a way to get around this limitation until an update to v10 is release with a fix? I need to be able to fetch a group using the path (string).

Or is there a way to make manual get requests from my app? I could not find anything documented and the `get` method on `groups` API class is protected. Would be great to have this ability, for any possible routes that are not supported by this package.

**Edit**: I found out how, for others incase:
```php
$response = GitLab::connection()->getHttpClient()->get('/api/v4/groups/'.rawurlencode($groupPath));
$group = ResponseMediator::getContent($response);
```

**Comment by GrahamCampbell** [comment]
Fixed.
