### ISSUE TITLE
Access levels should be named constants

### ISSUE THREAD

**Issue by mgrundkoetter** [m4tthumphrey/php-gitlab-api#571]
Instead of having the arbitrary integer values at several places hardcoded into the project and not accessible from outside, when using the api, [those values](https://docs.gitlab.com/ee/api/members.html#valid-access-levels) should exist as public constants in the API.

This may be in `Api/Projects` or `Api/Users` or inside a completely new class (like `AccessLevel`). So the usage would be like:
```
$gitlabApiClient->projects()->addMember(123, 123, AccessLevel::DEVELOPER);
# instead of
$gitlabApiClient->projects()->addMember(123, 123, 30);
```
This is much more intuitive and readable and code parts like 
```
... ->setAllowedValues('min_access_level', [null, 10, 20, 30, 40, 50])
```
will also be much more readable when using named class constants.

**Comment by GrahamCampbell** [comment]
Yep, that could be a good idea (for 10.1).
