### ISSUE TITLE
[10.x] iids is invalid

### ISSUE THREAD

**Issue by andrey-helldar** [m4tthumphrey/php-gitlab-api#573]
I am sending a request to get a list of comments for MR

Version 9.19 generated a request like this ([working](https://github.com/GitLabPHP/Client/blob/9.19/lib/Gitlab/HttpClient/Util/QueryStringBuilder.php#L26-L28)):
```
/api/v4/projects/31/merge_requests?iids[]=21
```

Version 10 makes a request like this ([doesn't work](https://github.com/GitLabPHP/Client/blob/10.0/src/HttpClient/Util/QueryStringBuilder.php#L25)):
```
/api/v4/projects/31/merge_requests?iids%5B0%5D=21
```

Therefore, the gitlab returns an error:
```
iids is invalid
```

```
{
    "error": {"type": "ValidationFailedException", "data": "iids is invalid"}, "info": {
    "exception": "Gitlab\\Exception\\ValidationFailedException",
    "file": "\/var\/www\/tunnel\/vendor\/m4tthumphrey\/php-gitlab-api\/src\/HttpClient\/Plugin\/GitlabExceptionThrower.php",
    "line": 60
}
```

**Comment by GrahamCampbell** [comment]
Fixed.

**Comment by andrey-helldar** [comment]
Thank you!

**Comment by GrahamCampbell** [comment]
9.19.1, 10.0.1 and 10.1.0 will be tagged soon.
