### ISSUE TITLE
Limited number of Merge Request commits

### ISSUE THREAD

**Issue by andrey-helldar** [m4tthumphrey/php-gitlab-api#577]
I have multiple Merge Request which has up to 150 commits.
Now, when asked, I get only 20. This is the number that Gitlab gives by default.

Of course, I could pass the `per_page` and` page` parameters by looping through the requests, but this cannot be done, since the [commits()](https://github.com/GitLabPHP/Client/blob/10.0/src/Api/MergeRequests.php#L368-L371) method does not accept additional parameters.

**Comment by GrahamCampbell** [comment]
You need to use the ResultPager class here. :)

**Comment by andrey-helldar** [comment]
It remains to figure out how to associate it with the `graham-campbell/gitlab` package:

![image](https://user-images.githubusercontent.com/10347617/94009676-77d77580-fdad-11ea-8317-4692f6903e91.png)

**Comment by andrey-helldar** [comment]
Found. The person asks the solution too :)
GrahamCampbell/Laravel-GitLab#28

**Comment by andrey-helldar** [comment]
Solved 😊

See https://github.com/GrahamCampbell/Laravel-GitLab/issues/28#issuecomment-697333027
