### ISSUE TITLE
Issues->addNote(): support additional params (confidential, created_at)

### ISSUE THREAD

**Issue by caugner** [m4tthumphrey/php-gitlab-api#584]
Currently, `Issue->addNote()` only supports the required parameter `body`:
https://github.com/GitLabPHP/Client/blob/964682b90d85e1bd94c83005603b86335ee4c311/src/Api/Issues.php#L160-L164

The GitLab API accepts the optional parameters `confidential` and `created_at`, which is especially useful when migrating issues over from another ticket system: https://docs.gitlab.com/ee/api/notes.html#create-new-issue-note

**Comment by caugner** [comment]
I solved it temporarily as follows:

```php
    /**
     * @param int|string $project_id
     * @param int        $issue_iid
     * @param string     $body
     * @param array      $params
     *
     * @return mixed
     */
    public function addNote($project_id, int $issue_iid, string $body, array $params = [])
    {
        $params['body'] = $body;
        return $this->post($this->getProjectPath($project_id, 'issues/'.self::encodePath($issue_iid).'/notes'), $params);
    }
```

**Comment by GrahamCampbell** [comment]
Fixed.
