### ISSUE TITLE
Use keepachangelog format

### ISSUE THREAD

**Issue by glensc** [m4tthumphrey/php-gitlab-api#590]
please consider using:
- https://keepachangelog.com/en/1.0.0/

mainly:
- use iso8601 dates

**Comment by GrahamCampbell** [comment]
I have considered it, but won't be changing it. That said, I am not against the change, I am just not going to do it myself. If you are interesting joining the core team of this repo, I would happy to add you so that you can edit the releases on GitHub and update the change log in git.

**Comment by glensc** [comment]
Ok, started with a 10.1 branch (it's current default branch):
- https://github.com/GitLabPHP/Client/pull/594

but this project contributing model is confusing a bit to me (and no CONTRIBUTING.md either).

1. what are active branches that this needs to be pushed to?
2. are they updated with a merge from lower branches?
3. or cherry-pick (and resolve conflicts) and update each branch?

**Comment by GrahamCampbell** [comment]
> but this project contributing model is confusing a bit to me (and no CONTRIBUTING.md either).

The contribution guide is in the new standard place: https://github.com/GitLabPHP/Client/blob/10.1/.github/CONTRIBUTING.md. When you create a new issue, GitHub will link to it in the bottom right of the screen, under "Helpful resources".

**Comment by GrahamCampbell** [comment]
> what are active branches that this needs to be pushed to?

This is defined by the fact we follow semver. Bug fixes to the current stable, new features to the next minor, and breaking changes to the next major.

**Comment by GrahamCampbell** [comment]
I am also continuing to apply fixes to the latest 9.x, where possible. I suppose this is not documented.

**Comment by glensc** [comment]
@GrahamCampbell did not get an answer on how you want the other branches to be updated:
- https://github.com/GitLabPHP/Client/issues/590#issuecomment-718913845

**Comment by glensc** [comment]
Seems you completed this with option 2:
- are they updated with a merge from lower branches?

i.e:
- https://github.com/GitLabPHP/Client/blob/10.2.0/CHANGELOG.md
- https://github.com/GitLabPHP/Client/blob/10.1.2/CHANGELOG.md

**Comment by GrahamCampbell** [comment]
I am not backporting this.
