### ISSUE TITLE
Pager is broken

### ISSUE THREAD

**Issue by Great-Antique** [m4tthumphrey/php-gitlab-api#592]
It seems that pager is broken in **10.1.0**.

There are two places for building resulting URI:
* [AbstractApi](https://github.com/GitLabPHP/Client/blob/10.1.0/src/Api/AbstractApi.php#L246-L252)
* [QueryStringBuilder](https://github.com/GitLabPHP/Client/blob/10.1.0/src/HttpClient/Util/QueryStringBuilder.php#L22-L30)

But `?` symbol isn't added in any of them. So resulting URI is `/api/v4/projects/5315609/repository/branchesper_page=50` (there is no `?` bewteen `branches` and `per_page=50`).

In **10.0.0** `?` is [added in QueryStringBuilder](https://github.com/GitLabPHP/Client/blob/10.0.0/src/HttpClient/Util/QueryStringBuilder.php#L25).
In **9.19.1** `?` is [added in AbstractApi](https://github.com/GitLabPHP/Client/blob/9.19.1/lib/Gitlab/Api/AbstractApi.php#L281).

I've added test in #591.

**Comment by GrahamCampbell** [comment]
Ah, thanks! That is definitely my fault! I reverted the changes to the query builder in 10.0.1 that were in 10.0.0, but forgot not all of the changes were good to revert, exactly for the reason you pointed out. :)

**Comment by GrahamCampbell** [comment]
Fixed in 10.0.2 and 10.1.1.
