### ISSUE TITLE
variable_type parameter missing in Projects::addVariable

### ISSUE THREAD

**Issue by pselge-daparto** [m4tthumphrey/php-gitlab-api#595]
It is currently not possible to add a project variable with the _variable type_ of _file_.
There would need to be an additional parameter in the Projects class https://github.com/GitLabPHP/Client/blob/0c7de45272e97da854162bcf85414cc047baa889/src/Api/Projects.php#L859

See: https://docs.gitlab.com/ee/api/project_level_variables.html#create-variable

Same goes for the update method on this line https://github.com/GitLabPHP/Client/blob/0c7de45272e97da854162bcf85414cc047baa889/src/Api/Projects.php#L886

See: https://docs.gitlab.com/ee/api/project_level_variables.html#update-variable

**Comment by GrahamCampbell** [comment]
Will be fixed in 10.2.0. :)
