### ISSUE TITLE
Using parameters creates wrong URLs

### ISSUE THREAD

**Issue by mquadrat** [m4tthumphrey/php-gitlab-api#598]
Sample Code: 

`$repos = $this->gitLab->projects()->perPage(100)->all();`

URL it should create: 

`<URL>/api/v4/projects?per_page=100`

URL it creates: 

`<URL>/api/v4/projectsper_page=100`

Code change to make it work (AbstractApi.php): 

`    private static function prepareUri(string $uri, array $query = [])
    {
        $query = \array_filter($query, function ($value): bool {
            return null !== $value;
        });

        return \sprintf('%s%s?%s', self::URI_PREFIX, $uri, QueryStringBuilder::build($query));
    }`

Can be fixed more elegant, especially not adding a ? at the end even if there is no query string.

**Comment by GrahamCampbell** [comment]
Please upgrade to the latest version. This has already been fixed. :)

**Comment by mquadrat** [comment]
A sorry, should have checked that. Somehow "10.1" ended up in my composer.json instead of "^10.1" and pinned me to the old one. My bad!
