### ISSUE TITLE
Missing support of the approved_by_ids filter option in MergeRequests

### ISSUE THREAD

**Issue by vbartusevicius** [m4tthumphrey/php-gitlab-api#599]
In the documentation https://docs.gitlab.com/ee/api/merge_requests.html there is a defined query parameter `approved_by_ids`, but in version 10.1 trying to filter by it throws exception: `The option "approved_by_ids" does not exist.`

**Comment by GrahamCampbell** [comment]
Please send a PR to our 10.2 branch to add support. :)

**Comment by vbartusevicius** [comment]
Maybe you know when you're planning to release 10.2?

**Comment by GrahamCampbell** [comment]
Probably around the end of November. You can still install it with `^10.2@dev` or just `^10.2` if you globally allow dev and prefer-stable, or something.
