### ISSUE TITLE
using block-method returns an Exception

### ISSUE THREAD

**Issue by FSD-Christian-ADM** [m4tthumphrey/php-gitlab-api#601]
the server's answer for blocking a user is a bool value but the API expects an array which lead to an exception
```

$gitlab = new Gitlab\Client();
$gitlab->setUrl('customgitlaburl');
$gitlab->authenticate($gitlab_api_access_token, Gitlab\Client::AUTH_HTTP_TOKEN);
$user = $gitlab->users()->all(array("username" => $username));
$gitlab->users()->block($user[0]["id"]);
```

Result:
PHP Fatal error:  Uncaught Gitlab\Exception\RuntimeException: json_decode error: Expected JSON of type array, bool given. in /home/gitlab_ad_usersync/include/gitlab_api/vendor/m4tthumphrey/php-gitlab-api/src/HttpClient/Util/JsonArray.php:33
Stack trace:
#0 /home/gitlab_ad_usersync/include/gitlab_api/vendor/m4tthumphrey/php-gitlab-api/src/HttpClient/Message/ResponseMediator.php(49): Gitlab\HttpClient\Util\JsonArray::decode('true')
#1 /home/gitlab_ad_usersync/include/gitlab_api/vendor/m4tthumphrey/php-gitlab-api/src/Api/AbstractApi.php(143): Gitlab\HttpClient\Message\ResponseMediator::getContent(Object(GuzzleHttp\Psr7\Response))
#2 /home/gitlab_ad_usersync/include/gitlab_api/vendor/m4tthumphrey/php-gitlab-api/src/Api/Users.php(200): Gitlab\Api\AbstractApi->post('users/78/block')
#3 /home. in /home/gitlab_ad_usersync/include/gitlab_api/vendor/m4tthumphrey/php-gitlab-api/src/HttpClient/Util/JsonArray.php on line 33

same for the unblock method.
blocking and unblocking is executed nonetheless

**Comment by GrahamCampbell** [comment]
Please can you run `composer show`, so I can see the installed packages.

**Comment by FSD-Christian-ADM** [comment]
> 
> 
> Please can you run `composer show`, so I can see the installed packages.

clue/stream-filter                v1.5.0  A simple and modern approach to stream filtering in PHP
guzzlehttp/guzzle                 7.2.0   Guzzle is a PHP HTTP client library
guzzlehttp/promises               1.4.0   Guzzle promises library
guzzlehttp/psr7                   1.7.0   PSR-7 message implementation that also provides common utility methods
http-interop/http-factory-guzzle  1.0.0   An HTTP Factory using Guzzle PSR7
m4tthumphrey/php-gitlab-api       10.1.1  GitLab API v4 client for PHP
php-http/cache-plugin             1.7.1   PSR-6 Cache plugin for HTTPlug
php-http/client-common            2.3.0   Common HTTP Client implementations and tools for HTTPlug
php-http/discovery                1.12.0  Finds installed HTTPlug implementations and PSR-7 message factories
php-http/httplug                  2.2.0   HTTPlug, the HTTP client abstraction for PHP
php-http/message                  1.9.1   HTTP Message related tools
php-http/message-factory          v1.0.2  Factory interfaces for PSR-7 HTTP Message
php-http/multipart-stream-builder 1.1.2   A builder class that help you create a multipart stream
php-http/promise                  1.1.0   Promise used for asynchronous HTTP requests
psr/cache                         1.0.1   Common interface for caching libraries
psr/http-client                   1.0.1   Common interface for HTTP clients
psr/http-factory                  1.0.1   Common interfaces for PSR-7 HTTP message factories
psr/http-message                  1.0.1   Common interface for HTTP messages
ralouphie/getallheaders           3.0.3   A polyfill for getallheaders.
symfony/deprecation-contracts     v2.2.0  A generic function and convention to trigger deprecation notices
symfony/options-resolver          v5.1.8  Symfony OptionsResolver Component
symfony/polyfill-php80            v1.20.0 Symfony polyfill backporting some PHP 8.0+ features to lower PHP versions

**Comment by harabisj** [comment]
I have same issue as @FSD-Christian-ADM. The Block user endpoint appaerently doesn't return JSON. https://docs.gitlab.com/ee/api/users.html#block-user

**Comment by FSD-Christian-ADM** [comment]
@GrahamCampbell Will there be any further updates on this?

**Comment by GrahamCampbell** [comment]
I think GitLab must have a bug in their API. Please report to them that they are adding a application/json content-type header to the response, but it is not JSON.

**Comment by GrahamCampbell** [comment]
We only attempt to decode the response if GitLab tell us it is JSON:

```php
    /**
     * The JSON content type identifier.
     *
     * @var string
     */
    public const JSON_CONTENT_TYPE = 'application/json';

    /**
     * Return the response body as a string or JSON array if content type is JSON.
     *
     * @param ResponseInterface $response
     *
     * @return array|string
     */
    public static function getContent(ResponseInterface $response)
    {
        $body = (string) $response->getBody();

        if ('' !== $body && 0 === \strpos($response->getHeaderLine('Content-Type'), self::JSON_CONTENT_TYPE)) {
            return JsonArray::decode($body);
        }

        return $body;
    }
```

**Comment by GrahamCampbell** [comment]
What exactly is returned for you? Are you able to add a var_dump to see what `$body` is, in your app?

**Comment by harabisj** [comment]
I tried to send request myself to the endpoint, got header `Content-Type: application/json` and body of `true`. So it's GitLab's bug.

**Comment by harabisj** [comment]
Reported to GL: https://gitlab.com/gitlab-org/gitlab/-/issues/290986

**Comment by GrahamCampbell** [comment]
Hmmm, newer specs for JSON say that that is actually valid JSON, but PHP's json_decode does not support it. We can probably work around this!

**Comment by harabisj** [comment]
However,
```
<?php
echo json_decode('true');
```
returns `1`, so it probably is supported by json_decode() as has been stated in the GL issue comments.

**Comment by GrahamCampbell** [comment]
Does version 10.3.1 work for you?

**Comment by FSD-Christian-ADM** [comment]
blocking and unblocking works like a charm now! Thanks for fixing this!

**Comment by harabisj** [comment]
Yes, it works perfectly. Thank you!

**Comment by GrahamCampbell** [comment]
Great.
