### ISSUE TITLE
Projects: Add missing order

### ISSUE THREAD

**Issue by bchatard** [m4tthumphrey/php-gitlab-api#603]
Hi,

Is it possible to add some missing `order_by` value for `\Gitlab\Api\Projects::all`?

https://github.com/GitLabPHP/Client/blob/0e158ba10365d91cccd0b1eca0b020827870dfd1/src/Api/Projects.php#L53

The missing values are related with "sudo" permissions : 
https://docs.gitlab.com/ee/api/projects.html#list-all-projects

I will see something like this:
```php
    public function all(array $parameters = [])
    {
        $resolver = $this->createOptionsResolver();
        $booleanNormalizer = function (Options $resolver, $value) {
            return $value ? 'true' : 'false';
        };
        $resolver->setDefined('archived')
            ->setAllowedTypes('archived', 'bool')
            ->setNormalizer('archived', $booleanNormalizer)
        ;
        $resolver->setDefined('visibility')
            ->setAllowedValues('visibility', ['public', 'internal', 'private'])
        ;
        $orderBy = ['id', 'name', 'path', 'created_at', 'updated_at', 'last_activity_at'];
        if (/* a beautiful function to test if Client is sudo */) {
            $orderBy = [...$orderBy, 'repository_size', 'storage_size', 'wiki_size'];
        }
        $resolver->setDefined('order_by')
            ->setAllowedValues('order_by', ['id', 'name', 'path', 'created_at', 'updated_at', 'last_activity_at'])
        ;
...
```

but I don't know how to easily check if Client has "sudo" parameter (seems only a header), so this request require some change on Client class.

Maybe I will try to do a PR

Thanks for your feedback :)

**Comment by GrahamCampbell** [comment]
Friendly ping @bchatard. Are you willing to send in a PR?

**Comment by bchatard** [comment]
hi, sorry I'm busy actually...
I only can create a PR to add "missing" fields for everyone (no check on "sudo").
Do you think it's an interesting PR even it's incomplete?

thanks

**Comment by GrahamCampbell** [comment]
I think that sounds fine, tbh.
