### ISSUE TITLE
Support PHP 8

### ISSUE THREAD

**Issue by arokettu** [m4tthumphrey/php-gitlab-api#604]
PHP 8 is released this Thursday. Please add support.

Tests seem to pass so apparently only the declaration in composer is required

**Comment by andypost** [comment]
Tests also needs fixes after matrix extended https://github.com/GitLabPHP/Client/blob/10.2/.github/workflows/tests.yml#L14

**Comment by GrahamCampbell** [comment]
Support for PHP 8 was blocked on our dependencies. I have made fixes in those over the last few months, and as of a week ago, or so, they are now ready. I will get around to adding PHP 8 here soon.

**Comment by GrahamCampbell** [comment]
Version 10.3.0 is out now, with support for PHP 8. Similarly, `graham-campbell/gitlab` version 4.3.0 is out too.
