### ISSUE TITLE
Is there a Way to support PHP8 in the 9.* Branch?

### ISSUE THREAD

**Issue by boredom2** [m4tthumphrey/php-gitlab-api#606]
Hi there,

thanks for your outstanding Work. I know, that Version 10 supports PHP8 already, but sadly, this Version cant be installed in our Environments, as there are really Tons of Dependency Issues with that. But we are currently migrating our Codebase to PHP8, so I just wanted to ask, if the 9.* Branch could support PHP8 too? From what we see, the Lib is working fine, but its not installable due to the Package Definition.

Thanks!

**Comment by GrahamCampbell** [comment]
The 9.x series is no longer maintained. Maybe I can help you with the upgrade. Which dependencies are blocking you?

**Comment by GrahamCampbell** [comment]
Before upgrading to PHP 8, I'd definitely recommend upgrading everything. Often times packages can be installed even if they don't work, too!

**Comment by boredom2** [comment]
Thats very kind, thank you!
But I decided to solve it myself and I was successfull - could overcome indeed the Dependency Issues.

Thank you very much!
