### ISSUE TITLE
ResultPager issue

### ISSUE THREAD

**Issue by Stdubic** [m4tthumphrey/php-gitlab-api#610]
Hi guys.

I have an issue with ResultPager, My code goes like this:

$client = new Client();
$pager = new ResultPager($client,20);
$issues = $pager->fetchAll($client->repositories(), 'commits', [11261183]);

and get back with the response array of all 700 commits not paged :(

Am I doing something wrong? Please help with this issue. Pagination is a must in my implementation of API.

**Comment by GrahamCampbell** [comment]
Yep, this is how the pager works (it does all the pagination behind the scenes so you don't have to see any pages). If you want to lazy iterate them, use the `fetchAllLazy` method (which will avoid loading all 700 in memory at once). :)

**Comment by Stdubic** [comment]
Thanks for the fast response and explanation :)
