### ISSUE TITLE
Add support to trigger a pipeline

### ISSUE THREAD

**Issue by sjadema** [m4tthumphrey/php-gitlab-api#611]
With #307, support for the Pipeline Triggers API was added. GitLab's [API](https://docs.gitlab.com/ee/api/pipeline_triggers.html) docs are missing the description to trigger a pipeline (using a trigger). Documentation about this can be found on a different [page](https://docs.gitlab.com/ee/ci/triggers/#triggering-a-pipeline) in their docs.

Would be awesome if we could trigger a pipeline as well.

**Comment by GrahamCampbell** [comment]
I'd accept a PR to implement this, with tests.

**Comment by sjadema** [comment]
Sure, i already implemented it for the project i needed it for. Tomorrow i'll backport it to this repo.

**Comment by sjadema** [comment]
Released in https://github.com/GitLabPHP/Client/releases/tag/11.1.0
