### ISSUE TITLE
Add support for ...ifExists on methods that might 404

### ISSUE THREAD

**Issue by sjadema** [m4tthumphrey/php-gitlab-api#613]
For our project, we're requiring either files or artifacts that might or might not exist. Using the API's endpoints (e.g. `$client->repositoryFiles()->getRawFile()`), i could check against the specific `RuntimeException` with code `404` but this adds a lot of boilerplate:

```php
try {
    $file = $client->repositoryFiles()->getRawFile(1, 'file.txt', 'master');
} catch (RuntimeException $e) {
    if (404 === $e->getCode()) {
        // Log something or whatever
        return;
    }
    
    throw $e;
}

// Continue with execution
```

My suggestion is to add `...IfExists()` methods for endpoints that might return 'nothing' so it removes some of the boilerplate. You loose the possibility of logging but if you're not worried about that, it might save you a lot of boilerplate:

```php
$file = $client->repositoryFiles()->getRawFileIfExists(1, 'file.txt', 'master');
if (null === $file) {
    // Log something or whatever
    return;
}

// Continue with execution
```

As you can see in the example, the methods would return `null` if the resource doesn't exist.

**Comment by sjadema** [comment]
@GrahamCampbell Hey man, not to push you or anything but do you think this is a good idea or should i keep this as a custom implementation on our side?

**Comment by GrahamCampbell** [comment]
GitLab can return 404 for other reaons than the file doesn't exist. Such as is if the current user doesn't have access to the repo, or the repo path is typoed. It is for this reason this library doesn't have a special exception for 404, nor does it implement the method you suggest.
