### ISSUE TITLE
MergeRequest API - invalid option for approved_by_ids

### ISSUE THREAD

**Issue by enp-bwrona** [m4tthumphrey/php-gitlab-api#617]
https://docs.gitlab.com/ee/api/merge_requests.html#list-project-merge-requests
```
approved_by_ids | integer array | no | Returns merge requests which have been approved by all the users with the given ids (Max: 5). None returns merge requests with no approvals. Any returns merge requests with an approval.
```
approved_by_ids should accept "none" and "any" values. Not just array.

**Comment by GrahamCampbell** [comment]
Do they mean to pass the literal string values `None` and `Any`?

**Comment by enp-bwrona** [comment]
Yes, you can pass _None_, _Any_ or array of integers
