### ISSUE TITLE
Date Release 11.1

### ISSUE THREAD

**Issue by cwandrey** [m4tthumphrey/php-gitlab-api#618]
Hello, 
when is the release of version 11.1 planned? 
I slowly need the change from https://github.com/GitLabPHP/Client/pull/615 

Thank you very much, 
Chris

**Comment by GrahamCampbell** [comment]
Not sure. You can still install it with `^11.1@dev` in the meanwhile. :)

**Comment by cwandrey** [comment]
all right. Thanks for your answer

**Comment by GrahamCampbell** [comment]
Something I am looking to solve before the release is https://github.com/GitLabPHP/Client/issues/617. There are lots of other places where this issue crops up. Any help with that would be appreciated.

**Comment by GrahamCampbell** [comment]
Released it anyway, without a fix in place for that other issue (that other issue is a long standing issue anyway).
