### ISSUE TITLE
Implement hook tag_push_events

### ISSUE THREAD

**Issue by chocopoche** [m4tthumphrey/php-gitlab-api#62]
The tag push events have been added to Gitlab API v7.4.0.rc1 (https://github.com/gitlabhq/gitlabhq/commit/b4963e9dda1ced7c219f24172e9fa4c8a5076b69)

What would be required to implement such feature? I was about to propose a merge request but I guess it's a bit more complicated and would require to implement all changes from Gitlab 6.9.1, according to the versionning policy. 

Thanks you

**Comment by m4tthumphrey** [comment]
Hey, I've just pushed an update for this. I will not be tagging a release just yet however as there is a few more bits I wish to clean up before tagging.
