### ISSUE TITLE
Projects:all parameter list is incomplete

### ISSUE THREAD

**Issue by aadmathijssen** [m4tthumphrey/php-gitlab-api#622]
When comparing the current list of attributes of the [`/projects` API endpoint](https://docs.gitlab.com/ee/api/projects.html#list-all-projects) to the [parameter list of the `\Gitlab\Api\Projects::all` class](https://github.com/GitLabPHP/Client/blob/11.1/src/Api/Projects.php#L25-L42), the following parameters are missing:
* `id_after` (integer)
* `id_before` (integer)
* `last_activity_after` (datetime)
* `last_activity_before` (datetime)
* `repository_checksum_failed` (boolean)
* `repository_storage` (string)
* `wiki_checksum_failed` (boolean)
* `with_custom_attributes` (boolean)
* `with_programming_language` (string)

**Comment by GrahamCampbell** [comment]
I'd accept a PR to the 11.2 branch to add anything that is missing. :)

**Comment by aadmathijssen** [comment]
Already working on it!

**Comment by aadmathijssen** [comment]
Here you go! :-)

**Comment by GrahamCampbell** [comment]
🍻
