### ISSUE TITLE
Tag search does not work, throws unkown option for "search"

### ISSUE THREAD

**Issue by tgerakitis** [m4tthumphrey/php-gitlab-api#626]
Hi, I have encountered an error,

by definition, the tags API allows the "search" parameter as seen here: https://docs.gitlab.com/ce/api/tags.html

My code
```
#this works
$branches = $client->repositories()->branches($projectId, [
    'search' => $search
]);

#this does not
$tags = $client->repositories()->tags($projectId, [
    'search' => $search
];

```
Throws this error:
`The option "search" does not exist. Defined options are: "page", "per_page", "type".`

**Comment by GrahamCampbell** [comment]
Looks like this has been done in v11.3.0. 🚢
