### ISSUE TITLE
pass curl_options to curl

### ISSUE THREAD

**Issue by thyseus** [m4tthumphrey/php-gitlab-api#627]
Hey,

is it possible to configure GitlabPHP to use curl as http client adapter ?
if so, it is possible to pass options like the much desired `CURLOPT_SSL_VERIFYPEER` option ?
I do not see a way to do this with the `$builder` pattern - or it is not documented.

Thanks in advance for any help !

**Comment by GrahamCampbell** [comment]
Yes. By default, we discover an http client automatically, but you can provide you own `Psr\Http\Client\ClientInterface` implementation as param 1 to the constructor of `Gitlab\HttpClient\Builder`.
