### ISSUE TITLE
All Issues doesn't seem to mean all Issues

### ISSUE THREAD

**Issue by blankster** [m4tthumphrey/php-gitlab-api#628]
First of all, thanks for your work!

I've tried to use it, but struggle with something: I would like to get all issues:

```
// Token authentication
$client = new Gitlab\Client();
$client->authenticate(GITLAB_TOKEN, Gitlab\Client::AUTH_HTTP_TOKEN);

// Results Pager
$pager = new Gitlab\ResultPager($client);

// Fetch all issues
$issues = $pager->fetchAll($client->issues(),'all');](url)
```
When I compare the count of the issues I get by the token generated based on my personal GitLab user, I don't see the same counts I see in Gitlab itself. I've lost hours searching for the problem and why it doesn't return me the same count of issues I see in the web-GUI of GitLab.

What could it be? Is there a kind of hidden filter set?

**Comment by GrahamCampbell** [comment]
I'm not sure. I can only recommend reading the gitlab source code itself, to get to the bottom of this.
