### ISSUE TITLE
Pipeline creation fails due to invalid parameters

### ISSUE THREAD

**Issue by IAL32** [m4tthumphrey/php-gitlab-api#638]
According to the documentation [here](https://docs.gitlab.com/ee/api/pipelines.html#create-a-new-pipeline), to create a pipeline this is the correct POST query:

`curl --request POST --header "PRIVATE-TOKEN: <your_access_token>" "https://gitlab.example.com/api/v4/projects/1/pipeline?ref=master"`

Currently though, the abstract API for the POST request does not handle correctly the `ref` query parameter:

```php
$response = $this->client->getHttpClient()->post(self::prepareUri($uri), $headers, $body);
```

As you can see, the `self::prepareUri($uri)` does not take into account the `ref` parameter from the `projects()->createPipeline` method.

Currently, `createPipeline` is the only place that I see that has this caveat.

**Comment by IAL32** [comment]
Not an issue, I was just putting the parameters wrong.

**Comment by IAL32** [comment]
Reopened, as the issue is still relevant, and a comprehensive PR is being made to fix it.

**Comment by GrahamCampbell** [comment]
Hmmm, GitLab should really fix this on their side. This is inconsistent with how all their other API routes behave.

**Comment by GrahamCampbell** [comment]
I'll merge your fix to unblock things, but I don't like it, lol. :)
