### ISSUE TITLE
Symfony 5.2+ PSR\Cache

### ISSUE THREAD

**Issue by acassan** [m4tthumphrey/php-gitlab-api#647]
It seem PSR 2.0 is now by default on new symfony app (5.2+) and bundle no more compatible with the PSR 2.0 version.

` m4tthumphrey/php-gitlab-api 11.5.x-dev requires psr/cache ^1.0 -> found psr/cache[1.0.0, 1.0.1] but the package is fixed to 2.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update `command.``

Any work in progress on this ?

**Comment by GrahamCampbell** [comment]
Thanks for the report. I think this'll require upstream changes first.

**Comment by Jir4** [comment]
Hello,

**Comment by Jir4** [comment]
Hello, when you said 

> Thanks for the report. I think this'll require upstream changes first.

Did you think it may require to update this package to be php 8.0 ready ?

**Comment by GrahamCampbell** [comment]
No.

**Comment by lairg99** [comment]
What is the current status here?

**Comment by GrahamCampbell** [comment]
It is still possible to use psr cache v1, so this was never a blocker. The only issue is that composer would not automatically downgrade it for you - you'd have to first downgrade it yourself, or install this package by hand in the composer.json, and run a full `composer update`. In any case, support for v2 is coming in the next release. I should also point out this is not related to PHP 8.0 or 8.1 support nor does it require us to drop support for PHP 7. Composer will download whatever packages are most suitable for you based on your system PHP version, extensions, and peer dependency requirements.
