### ISSUE TITLE
Enable group runner missing in api

### ISSUE THREAD

**Issue by KameKam** [m4tthumphrey/php-gitlab-api#649]
Hello
I'm making a python script to create a project with a import of a template project, until now everything is ok. When I try to run a pipeline through script, it's stuck because group runners are disabled by default in our gitlab. I seek many site and docs to find solution but no result or maybe i used them wrong.
![110px-Python-logo-notext svg](https://user-images.githubusercontent.com/49527647/121362297-49e39280-c936-11eb-8fa7-b52e008e2272.png)
I found this solution but doesn't work and I got reply from the github of python-gitlab that's say that this feature doesn't exist in api to have it in python-gitlab. Do you know if it's planed to add this feature and if yes when please. 
Otherwise great job the api is very useful , thanks a lot for your job

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch. I don't know what GitLab's internal product roadmap looks like. Sorry.
