### ISSUE TITLE
The pager doesn't fetch the information correctly and is inconsistent

### ISSUE THREAD

**Issue by FredVaugeois** [m4tthumphrey/php-gitlab-api#650]
Hi! I am currently facing an issue regarding the pager for the GitLab API. Basically, all I want to do is to get the last branch of one of my repositories. I have tried a lot of ways to do it.

The first one I tried is using fetchall like this:

```php
$branches = $pager->fetchAll($this->gitlab->repositories(), 'branches', [$id, ['search' => '^foo']]);
rsort($branches);
return $branches[0];
``` 
which works as intended *most of the time*. The problem is that it does not work *all the time* which is a real issue. It has a lot of problems especially when there has been an update in the repository a few moments before fetching the results. I know that there are some issues regarding the maximum number of values per page, but using fetchall, from what I understand, should bypass the maximum nubmer of values per page. Although, when it doesn't work, it only fetches the default number of values per page (50).

The other method I tried is using a simple fetch, then doing a fetch last and getting the last element of the last page like this:

 ```php
 $pager->fetch($this->gitlab->repositories(), 'branches', [$id, ['search' => '^foo']]);
 $lastPage = $pager->fetchLast();
 return end($lastPage);
 ```
 which again, works *most of the time*. The behavior of this method is even more weird: it detects that I have multiple pages, but when I'm on a page that contains items of indexes above 50, the page is empty. So `end($lastPage)` returns false (empty array). So I think that it is extremely weird that the pager knows that there are values beyond 50 (because it 'creates' more pages to store them) but doesn't actually store them appropriately. 
 
 The workaround that I am currently using works (for now) all the time, but it a very ugly fix and I would like to change it as soon as this issue is resolved:
 
 ```php
$maxIterations = 5;
$secondsInterval = 10;
// Iterate until it works or 'times out'
for($i = 0; $i < $maxIterations; $i++) {
    $pager->fetch($this->gitlab->repositories(), 'branches', [$id, ['search' => '^foo-']]);
    // Then, we want to get the last page of the results (because for some reason, it can't stick it on a single page
    // because by default, the maximum elements per page is 50). What's weird is that even tho it knows that the
    // other pages do exist, their list of values is empty. Because why not.
    $lastPage = $pager->fetchLast();
    // Now try to get the last result of the array of branches of our last pager's page. If it returns false, it
    // means that the array is empty. So we need to try that until it stops being retarded and does indeed fetch
    // all of the information like a normal API being.
    if(end($lastPage)) {
        return end($lastPage);
    }
    // If it does not have the list of values, sleep a little and wait again
    sleep($secondsInterval);
}
return null;
```

Thank you!

**Comment by Mmasson-01** [comment]
I believe this was not resolved !

**Comment by peterjaap** [comment]
Running in to the same! It's the merge request entity for me but I guess that's irrelevant.

**Comment by peterjaap** [comment]
I just discovered that when i add scope=all to the params, it does work consistently.
