### ISSUE TITLE
Is there any readable documentation available? 

### ISSUE THREAD

**Issue by sibidharan** [m4tthumphrey/php-gitlab-api#657]
Unable to assume all functions that exist!

**Comment by GrahamCampbell** [comment]
Honestly, you should find the code self-documenting + GitLab's API docs, in combination with the examples on the README. Please let me know if there's anything I can do to make that process easier.

**Comment by GrahamCampbell** [comment]
I don't have the time to maintain a copy of GitLab's API docs, or feel the need to do that. They can do a better job than me. Moreover, the valid parameters actually verify depending on the GitLab API version.

**Comment by sibidharan** [comment]
Understood, thanks.
