### ISSUE TITLE
I cannot connect via SSL (GuzzleHttp\Client verify false)

### ISSUE THREAD

**Issue by glebsergeevich** [m4tthumphrey/php-gitlab-api#668]
How can I disable http certificate validation?

Error:
`
cURL error 60: SSL certificate problem: unable to get local issuer certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)
`

I need an example how to connect it to the Gitlab php class. 

`
$client = new \GuzzleHttp\Client([
	'verify' => false,
]);
`

**Comment by GrahamCampbell** [comment]
I don't want to encourage this and provide an easy example. Correct certificate handling is easy in 2021.
