### ISSUE TITLE
Projects API: The ability to list/add/remove protected tags is missing.

### ISSUE THREAD

**Issue by internalsystemerror** [m4tthumphrey/php-gitlab-api#678]
There are some missing methods from the Projects API which I will create a PR for accompanying this issue.

First with regards to protected branches:
- Missing ability to [unprotect branches](https://docs.gitlab.com/ee/api/protected_branches.html#unprotect-repository-branches)

But mainly the protected tags are not yet implemented:
- Missing ability to [retrieve list of protected tags](https://docs.gitlab.com/ee/api/protected_tags.html#list-protected-tags)
- Missing ability to [protect tags](https://docs.gitlab.com/ee/api/protected_tags.html#protect-repository-tags)
- Missing ability to [unprotected tags](https://docs.gitlab.com/ee/api/protected_tags.html#unprotect-repository-tags)

**Comment by GrahamCampbell** [comment]
I'd accept a PR to implement this.

**Comment by internalsystemerror** [comment]
@GrahamCampbell I offered one. You said I needed to document some parameters. I asked for clarification as I couldn't find any existing parameter documentation and I'd just copied the `protectedBranches` method. I don't think you noticed that I'd asked anything as you closed the PR unmerged.

I'm no longer using this library, but those commits should still be available to you. glhf.

**Comment by GrahamCampbell** [comment]
Yeh, I'm aware. If anyone else wants to pick this up, they're welcome to. Open source is everyone's codebase. I won't personally be doing this, in this instance. :)
