### ISSUE TITLE
Add cache support

### ISSUE THREAD

**Issue by dkarlovi** [m4tthumphrey/php-gitlab-api#742]
Much like Github has.

https://github.com/KnpLabs/php-github-api#cache-usage

**Comment by GrahamCampbell** [comment]
We already have cache support. It works in the same way.

**Comment by GrahamCampbell** [comment]
Well, almost the same way. We don't expose it on the client class itself. You have to pass an http client builder into the constructor of the client, having added the cache plugin to it.

**Comment by GrahamCampbell** [comment]
```php
$builder = new Gitlab\HttpClient\Builder();
$builder->addCache($cache);
$client = new Gitlab\Client($builder);
```

**Comment by dkarlovi** [comment]
Ah, should have checked myself, sorry for the churn and thanks for the reply!
