### ISSUE TITLE
Create Personal Access Tokens

### ISSUE THREAD

**Issue by ryangurn** [m4tthumphrey/php-gitlab-api#749]
I could be wrong, but currently there does not appear to be a method to create a personal access token for a user.

https://docs.gitlab.com/ee/api/users.html#create-a-personal-access-token

Does this functionality exist or should it be added?

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch. You are correct in that this doesn't exist in this package at current.

**Comment by GrahamCampbell** [comment]
Closing since this issue is stale.
