### ISSUE TITLE
Allow to filter project labels

### ISSUE THREAD

**Issue by thomasmeulenbroek** [m4tthumphrey/php-gitlab-api#763]
I would like to be able to filter project labels on include_ancestor_groups, unfortunately i get an error stating that only page and per_page are allowed. Is there a way to add filters that aren't explicitly declared?

Thanks.

**Comment by GrahamCampbell** [comment]
No, but we would consider a PR to declare the parameters you want.

**Comment by GrahamCampbell** [comment]
Closing since this issue is stale.
