### ISSUE TITLE
Cannot download artifacts for job with space in its name

### ISSUE THREAD

**Issue by wilkolazki** [m4tthumphrey/php-gitlab-api#774]
Hi,

It is impossible to download artifacts using `Jobs::artifactsByRefName` and `Jobs::artifactByRefName`, because the space in jobs name is double-encoded to `%2520` instead of `%20`. 

I've created pull request #773 with fix to this issue.

**Comment by GrahamCampbell** [comment]
Fixed in 11.10.1, 11.11.1, 11.12.0.
