### ISSUE TITLE
[BUG] Missing author parameter on repositories()->commits()

### ISSUE THREAD

**Issue by mjadsmurai** [m4tthumphrey/php-gitlab-api#776]
As documentation states, there's an author parameter:
https://docs.gitlab.com/ee/api/commits.html

But this SDK is missing it:
https://github.com/GitLabPHP/Client/blob/11.11/src/Api/Repositories.php#L203

When i try to use it, it throws an exception saying that `author` doesn't exist.

```php
$client->repositories()->commits($projectId, [
    "author" => "demo@demo.com"
]);
```

DIrect curl requests against /repositories/commits with `author` parameter do work, so it's just missing in this sdk definition :o

**Comment by GrahamCampbell** [comment]
Fixed in 11.12.0
