### ISSUE TITLE
urlencode() -> rawurlencode()

### ISSUE THREAD

**Issue by m4tthumphrey** [m4tthumphrey/php-gitlab-api#81]
Replace all usage of `urlencode()` to `rawurlencode()`

**Comment by paolomainardi** [comment]
@m4tthumphrey the idea is to replace all occurrences of urlencode() to rawurlencode() ?

**Comment by m4tthumphrey** [comment]
Yes, your MR just gave me the push I needed to get around to updating it!

**Comment by paolomainardi** [comment]
@m4tthumphrey can i take in charge this issue ?

**Comment by m4tthumphrey** [comment]
Of course! :)

**Comment by paolomainardi** [comment]
PR: https://github.com/m4tthumphrey/php-gitlab-api/pull/82

**Comment by m4tthumphrey** [comment]
@paolomainardi Are you still planning on completing this for all of the API endpoints?

**Comment by paolomainardi** [comment]
@m4tthumphrey yes but probably you missed this MR: https://github.com/m4tthumphrey/php-gitlab-api/pull/82 :)

**Comment by m4tthumphrey** [comment]
No I did see it but it only has the project endpoints updated at the moment...?

**Comment by paolomainardi** [comment]
It covers also the other endpoints: 
https://github.com/m4tthumphrey/php-gitlab-api/pull/82/files

**Comment by m4tthumphrey** [comment]
Ah yes so it does, I'm sorry!
