### ISSUE TITLE
function encodePath problem

### ISSUE THREAD

**Issue by bartoszx** [m4tthumphrey/php-gitlab-api#89]
I think there is something wrong with function encodePath in AbstractApi.php line 122
As Gitlab documentation says "make sure that the NAMESPACE/PROJECT_NAME is URL-encoded, eg. /api/v3/projects/diaspora%2Fdiaspora (where / is represented by %2F)."

line: rawurlencode($path); encodes path as documentation describes and 
line: return str_replace(array('%2F', '.'), array('/', '%2E'), $path)
changes it back

result is 404 error 
[07/May/2015:20:29:31 +0200] "GET /api/v3/projects/dd/dd?private_token=

I use earlier version of php-gitlab-api in one of my projects and it works fine

**Comment by m4tthumphrey** [comment]
Ah crap, I'll sort a fix for this tomorrow. It seems that the reason for the code in the `encodePath()` method only applies to the branch endpoints.

**Comment by bartoszx** [comment]
Hi @m4tthumphrey 
Have you found some time to fix this?

**Comment by m4tthumphrey** [comment]
Agh I'd completely forgotten to be honest. I'll do it now!

**Comment by m4tthumphrey** [comment]
Should be good now!

**Comment by bartoszx** [comment]
Thank you :)
