### ISSUE TITLE
Where do i get gitlab access_token

### ISSUE THREAD

**Issue by pavankumarkatakam** [m4tthumphrey/php-gitlab-api#93]
I have install gitlab CE in my local server and i also wanted to develop an php based application for using gitlab as Oauth2service provider . so im wondering how it will be achieved. I got up with this package and read all the documentation in read me file but one question remains me to start nothing that is where do i get a token. i have created a application in my gitlab and i have now app-id , secrete and callback url.. please help me.

**Comment by pavankumarkatakam** [comment]
After reading this doc i got the answer and working now 
http://doc.gitlab.com/ce/api/oauth2.html

but in this package there is no feature for getting the private or access-code by athuentication. can anybody explain this.

**Comment by m4tthumphrey** [comment]
@pavankumarkatakam When this library was first written, the OAuth functionality wasn't around, you only had access via the users private token so it was assumed that you would already know what your token was. There are plenty of OAuth libraries for PHP out there so you should be able to obtain one without this library directly.
