### ISSUE TITLE
Problem when fetching group members

### ISSUE THREAD

**Issue by khrizt** [m4tthumphrey/php-gitlab-api#97]
Hi,

I found a problem when using the api to get group members, doing this query

```php
$groupMembers = $this->gitlabClient->api('groups')->members($groupId, 1, 200);
```

I found that the response headers were truncated somehow and the headers returned this item:

```
Array
(
    [0] => HTTP/1.1 200 OK
    [1] => Date: Tue, 30 Jun 2015 13:38:01 GMT
    [2] => Server: Apache
    [3] => Link: <http://gitlab.fake/api/v3/groups/11/members?page=1&per_page=200>; rel="first", <http://gitlab.fake/api/v3/groups/11/members?page=1&per_page=200>; rel="last"
    [4] => Cache-Control: max-age=0, private, must-revalidate
    [5] => X-Request-Id: 4a04e42a-38cd-4154-8379-d6dd98ff83ac
    [6] => X-Runtime: 0.233594
    [7] => X-Powered-By: Phusion Passenger 4.0.57
    [8] => X-Frame-Options: SAMEORIGIN
    [9] => Content-Length: 6075
    [10] => ETag: "3dc10d7325d764b4ff657fa0e5227142"
    [11] => Status: 200 OK
    [12] => Content-Type: applicatio
)
```

Doing a little research I found that the problem seems to be in the __populateResponse__ method of the Buzz\Client\AbstractCurl class, in this method makes the following control structure

```php
        if (version_compare($version['version'], '7.30.0', '<')) {
            $pos = strlen($raw) - curl_getinfo($curl, CURLINFO_SIZE_DOWNLOAD);
        } else {
            $pos = curl_getinfo($curl, CURLINFO_HEADER_SIZE);
        }
```

And in my case the $pos variable has 10 characters less than it should have so the headers are truncated and therefore no json_decode is applied to the current response. I know it's not probably your responsibility, more a [Buzz library](https://github.com/kriswallsmith/Buzz) problem. But I wanted to note it here also if you know or can think of a solution.

Thanks

**Comment by m4tthumphrey** [comment]
Wow, nice find! There is an open issue #50 regarding the ability to set a specific HTTP adaptor so Buzz will no longer be a requirement. Unfortunately there is no timeframe for this at this time.

**Comment by khrizt** [comment]
Cool, that would be a great improvement.

Anyway I found a workaround for this problem but when doing the query to get the users' email the response did not include this parameter email neither when doing a group/id/members nor doing a member/id/show, do you know anything about that? It looks like a gitlab problem but... you never know :P

**Comment by m4tthumphrey** [comment]
@khrizt I would presume that's by design as users probably wouldn't want their email address to be easily accessible.

PS, sick avatar!

**Comment by khrizt** [comment]
Hahaha, thanks for the avatar.

I undestand that this could be a design thing but in their documentation it says that email should come in the response, I opened an issue there (https://github.com/gitlabhq/gitlabhq/issues/9421). Maybe someone will answer.

Thanks for everything man!

**Comment by m4tthumphrey** [comment]
Which endpoint are you using to get the email address? `/users` or `/users/:id` ? I've just done a raw request on one of my gitlab installs at `/users' and the email address is included. Are you an admin of the gitlab your using?

**Comment by khrizt** [comment]
mmmm that's it! I should have known :P Thanks a lot mail I'll close the issue I created.

**Comment by khrizt** [comment]
I close this one as there is an issue for chosing HTTP adapters
