### ISSUE TITLE
How many commits I can get?

### ISSUE THREAD

**Issue by DrWifey** [m4tthumphrey/php-gitlab-api#98]
I'm trying to get commits of a project via PHP. I got all commints for the today date. How can I get all of them? Thanks

**Comment by m4tthumphrey** [comment]
Hey!

There are pagination arguments available on the `commits()` [method](https://github.com/m4tthumphrey/php-gitlab-api/blob/master/lib/Gitlab/Api/Repositories.php#L100). I'm not sure if there is a maximum limit on the number of results you can request per page, probably not. If there is a limit you will need to write a loop which will call the method as many times as required based on the total number of commits.
